sbi-dev/sbi

- examples/snpec_linear_Gaussian.ipynb
- lfi/inference/apt.py
- lfi/simulators/linear_gaussian.py
- added notebook in examples/
- reduced number of samples to estimate acceptance ratio from 1e7 to 1e5
- added normalization_parameters() function to linear_gaussian.py
> Linear Gaussian 3D example APT

- .travis.yml
- environment.yml
- setup.cfg
- setup.py
* Rename `lfi` conda env to `sbi`
* No version pining in `environment.yml`
- install possible for people on OSX which does not have `cudatoolkit>=10`
- easier to transfer to travis
* Moved test_requires (should be anyways tests_require) into an extras_requires as per https://stackoverflow.com/a/27271396 and to match `dev` entry by @jan-matthis (may make easier for pip users)
* Future work: consider splitting `environment.yml` into release, development and test environments.
Closes #9.
> Install deps

- examples/snpec_linear_Gaussian.ipynb
- examples/snpec_twoMoons.ipynb
- sbi/inference/apt.py
- sbi/utils/__init__.py
- sbi/utils/get_models.py
- sbi/utils/sbi.py
- tests/test_linearGaussian_apt.py
- tests/test_twoMoons.py
- z-scoring of observations/contexts
- embedding net is now part of pyknos
- pilot samples
- simulation_per_round can be a list for each round
- in validation set, the remaining samples are dropped if they do not fill a full batch
- normalization of parameters theta relies on prior, not on samples
- updated notebook examples and tests
> APT observation z-scoring and embedding_net

- .github/workflows/testing.yml
- environment.yml
- sbi/inference/snpe/sbi_MDN_posterior.py
- sbi/inference/snpe/sbi_flow_posterior.py
- sbi/mcmc/slice.py
- sbi/simulators/simutils.py
- sbi/utils/get_models.py
- sbi/utils/get_sbi_models.py
- setup.py
This establishes sbi's dependency on nflows indirectly through pyknos.nflows rather directly to nflows.
The idea is that we will have access to a variety of density estimators via pyknos, one class of which is provided by nflows.
We currently use nflows as provided by our local fork, mackelab/nflows
@janfb @michaeldeistler could you :eyes: this? Ideally install sbi from scratch with conda and / or pip and check that tests pass.
> Rewired nflows imports to pyknos.nflows

- sbi/mcmc/slice.py
- tests/mcmc_slice_pyro/LICENSE.md
- tests/mcmc_slice_pyro/common.py
- tests/mcmc_slice_pyro/conftest.py
- tests/mcmc_slice_pyro/test_slice.py
Updates the slice sampling kernel Conor wrote for Pyro:
- It's now closely following the [design of the NUTS kernel](https://github.com/pyro-ppl/pyro/blob/dev/pyro/infer/mcmc/nuts.py), e.g., accepts passing `model` instead of just `potential_fn`
- It got faster by avoiding creation of unnecessary copies of `params` and cleaning up the code
- Added keywords arguments (e.g., for `initial_width`). The number of bracket tuning steps is now determined by `warmup_steps`
- Tests for the Slice kernel are part of the PR as well. They are Pyro's tests used for `NUTS`. Running all enabled tests takes about 20 seconds
- Some features, e.g., allowing for multiple sampling sites, are yet missing. The idea is to work this in over time and potentially contribute the kernel to Pyro at some point if they …
> Update Slice kernel

- .github/workflows/testing.yml
- setup.cfg
- tests/test_linearGaussian_snl.py
- tests/test_linearGaussian_sre.py
- tests/test_nonlinearGaussian_apt.py
- tests/test_twoMoons_apt.py
Added facility to mark tests as slow. 
* in setup.cfg, introduce a marker
* decorate affected functions as @pytest.mark.slow
* call whenever testing should be faster, pytest -m "not slow" instead of just pytest.
The current selection of functions is just a proposal. Also, we should build this into the automated CI. I would like to kindly ask @janfb, @jan-matthis to review these changes and ggf. commit a) a better selection of slow functions b) a new policy for the CI.
> Example marking of slow tests

- sbi/inference/snpe/snpe_base.py
The assert is not necessary since the batch_size is clipped in the data loader construction. Leaving it in can lead to unexpected behaviour.
> Remove assertion

- sbi/inference/snl/snl.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/sre/sre.py
- sbi/simulators/simutils.py
- tests/simulator_utils_test.py
If there are more pilot samples than simulations needed in first round 0 will be passed to `simulate_in_batches`. this is avoided here.
> Fix pilot samples recycling round 1. 

- sbi/inference/base.py
- sbi/inference/posteriors/sbi_posterior.py
- sbi/inference/snl/snl.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_b.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/sre/sre.py
- sbi/simulators/linear_gaussian.py
- sbi/simulators/nonlinear_gaussian.py
- sbi/simulators/simulator.py
- sbi/simulators/simutils.py
- sbi/utils/__init__.py
- sbi/utils/get_nn_models.py
- sbi/utils/logging.py
- sbi/utils/sbiutils.py
- sbi/utils/torchutils.py
- tests/conftest.py
- tests/linearGaussian_simulator_test.py
- tests/linearGaussian_snl_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_sre_test.py
- tests/nonlinearGaussian_snpe_c_test.py
- tests/simulator_utils_test.py
- tests/torchutils_test.py
- tests/utils_for_testing/linearGaussian_logprob.py
Refactor all variables to `theta`, `x`, `x_o`
- `context` and `inputs` are still used when the neural_net is called. This is part of pyknos or nflows and will have to go in another PR
- `x_o` is currently only used as in singular
- when variables are batched as `(N, size_of_a_single_theta_or_x)` with `N>1` we use `thetas` and `xs`
- when variables are batched as `(1, size_of_a_single_theta_or_x)` we use `theta` and `x`
- when variables are not batched, i.e. `(size_of_a_single_theta_or_x)` we also use `theta` and `x`
- when it is unclear which of the above cases apply (e.g. user inputs such as to `log_prob()` where our code can handle different cases), I decided on a "most reasonable scenario" and named them accordingly.
- `self.x_o` in `Posterior` class is not protected anymore. Before: …
> [WIP] Renaming variables to theta, x, x_o

- sbi/inference/snpe/snpe_base.py
- sbi/simulators/simutils.py
- sbi/utils/sbiutils.py
- tests/conftest.py
- tests/simulator_utils_test.py
prior float type is not checked for `Distribution` priors. This will result in float type erros down in sbi if a user manages to define a PyTorch prior with return type `float64`. 
In this PR we add the corresponding checks, wrappers and tests. 
In this process we have noticed issue #135 
This PR fixes the checks and wraps a float64 prior into float32. issue #135 will be handled in a separate PR.
> Check prior floattype

- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_b.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- tests/linearGaussian_snpe_test.py
Just a simple fix with accompanying test.
Note that the test demonstrates that deterministic simulators lead to infinites in log prob posterior, which we currently catch with an assertion.
Bundling management of z-scoring into a method and reducing complexity of the API by merging  `num_pilot_sims` and `z_score_x` into a single argument will be the subject of a subsequent PR.
> Z score fix deterministic sims

- sbi/inference/base.py
- sbi/inference/snl/snl.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_b.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/sre/sre.py
- sbi/user_input/user_input_checks.py
- tests/user_input_checks_test.py
Add a keyword arg in `base.py` to passed to user input checks that turns off
all input checks. This is useful for saving simulation budget.
- add flag and pass it through
- add warning
- add test
- cosmetics in tests: replace torch.ones by ones, etc.
> add kwarg to turn off input checks.

- sbi/inference/snl/snl.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/sre/sre.py
- sbi/user_input/user_input_checks.py
- sbi/utils/get_nn_models.py
- tests/linearGaussian_snl_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_sre_test.py
Density estimator utils like `utils.get_nn_models.posterior_nn()` used to get `prior` and `x_o` as args, allowing for passing unchecked prior and observation when used outside of sbi (e.g. in tests). See issue #135 .
Pass to density estimator utils only what is needed: 
- prior mean and std for constructing the standardize transform in `posterior_nn` 
- theta shape and x shape in `likelihood_nn` and 'classifier_nn`. 
- adapt usage in `inference` 
- adapt tests. 
- closes #135 
With the help of @meteore I think I can improve on the naming / new docstrings in the changed utils functions.
> Pass prior statistics and shapes to density estimator utils directly.

- sbi/inference/posteriors/sbi_posterior.py
- sbi/inference/snl/snl.py
- sbi/inference/snpe/snpe_b.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/sre/sre.py
- tests/linearGaussian_snl_test.py
- tests/linearGaussian_sre_test.py
- tests/simulator_utils_test.py
- tests/torchutils_test.py
replace `torch.zeros` by `zeros` in most files, same for `torch.ones` and `torch.eye`.
Related to #153 
One approval and I will merge it.
> refactor torch zeros, ones and eye imports.

- .gitignore
- .vscode/.ropeproject/config.py
- .vscode/autodocstring.template
- .vscode/extensions.json
- .vscode/settings.json
- environment.yml
Condition for merge: review from **ALL**.
This has costed me a good few hours because of byzantine interactions and weird bugs. Hence, I request your help in testing and finding solutions (see issues below)
Get this branch locally and switch to it. Be sure to create a `.env` file in the root of your repo, along these lines:
```
CONDA=/home/alvar/Local/miniconda3/envs/sbi
PYTHON=${CONDA}/bin/python
#XXX Some of these may not be necessary at all. Comment in `settings.json` to check
BLACK=${CONDA}/bin/black
ISORT=${CONDA}/bin/isort
FLAKE8=${CONDA}/bin/flake8
```
* flake8 does not play well with the default whitespace on empty lines on VSCode, at least not here. Could somebody investigate a setting to turn off the mustard-colored wiggly underlines? (or fix the insertion of whitespaces from …
> Local config for all users of vscode.

- sbi/inference/base.py
- sbi/inference/posteriors/sbi_posterior.py
- sbi/inference/snl/snl.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/sre/sre.py
- sbi/types.py
- sbi/utils/sbiutils.py
- sbi/utils/torchutils.py
- tests/linearGaussian_snl_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_sre_test.py
- tests/torchutils_test.py
- tests/utils_for_testing/linearGaussian_logprob.py
This
- updates docs and comments in `sbi_posterior.py`
- fixes a bug when `x` and `self.x_o` are both None
- simpIifies substantially `get_leakage_correction`
- provides more information to the user when warning that leakage is high
- makes leakage threshold for warning a settable argument
- replaces `atleast_2d` with an arity 1 function that does not type-convert (old function is now `atleast_2d_many`, may want to deprecate).
- fixes a couple of typos (missing `_`, extra `,`) that would result in bugs (and where not caught by the tests...).
Happy to have a pair of eyes glance over, and merge quickly.
> Leakage correction

- sbi/inference/snpe/snpe_b.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- closes #182 
- closes #183 
- calibration kernel was not applied in round 0
- instead it was added in round > 0 for snpe b and c
- now it is used in one place in snpe base, irrespective of snpe abc.
> Add function for calibration kernel loss to snpe base.

- sbi/inference/posteriors/sbi_posterior.py
- tests/linearGaussian_snl_test.py
- explain that mcmc samplers are always used by SRE and SNL, but only for dealing with leakage in SNPE
- fixed bug where `warmup_steps` was called `warmup`
- updated the docstring of the `posterior` class. Feedback very welcome here!
- implements `log_prob` for SNL (unnormalized of course). There is not yet a test for this because KL-D does not work on unnormalized densities. Visual inspection of the `log-prob() `output showed that it worked though.
> Documentation of MCMC samplers and log_prob for SNL

- sbi/inference/base.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- sbi/simulators/simutils.py
- sbi/utils/__init__.py
- sbi/utils/sbiutils.py
- tests/inference_with_NaN_simulator_test.py
- tests/linearGaussian_snpe_test.py
- tests/simulator_utils_test.py
This handles NaN simulations that simulators might return for invalid simulations. This is needed in sbibm where some ODE solvers fail for some parameters. 
- exclude nan x from theta and x banks 
- exclude nan in z_scoring
In principle, snpe would have another way of dealing with nan simulations - the calibration kernels. But these are not available in SRE and SNL, so this is a quick way to have binary calibration kernel (implicitly) for all inference algs. 
closes #184 
closes #210
> handle NaN data by excluding it from training.

- sbi/inference/base.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- sbi/utils/get_nn_models.py
- before this PR, the optimizer was still pointing to the wrong neural network when using `retrain_from_scratch_each_round`
- re-initialize the optimizer if `retrain_from_scratch_each_round`
- implement `retrain_from_scratch_each_round` for SNLE
- hence, all algorithms now have a `retrain_from_scratch_each_round` option -> moved it to `NeuralInference`.
- for SNPE_C, the performance is very poor when using `retrain_from_scratch_each_round`. It is unclear to me why, I am raising a warning in this case.
> Fix retrain_from_scratch bug

- .vscode/settings.json
- README.md
- docs/docs/credits.md
- docs/docs/index.md
- sbi/inference/base.py
- sbi/inference/posterior.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/mcmc/mcmc.py
- sbi/user_input/user-input-checks.md
- sbi/user_input/user_input_checks.py
- tests/inference_with_NaN_simulator_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/posterior_nn_test.py
- tests/test_utils.py
- tests/user_input_checks_test.py
* Renamed algorithm to (inference) method throughout.
* `freeze` is now `set_default_x`, closer to actual semantics. Further PR will make the difference between amortised and focused posterior.
* Cross-check of docstrings in `NeuralPosterior` please have a look in case I oversaw something.
> Docstrings, rename algorithm->method, __repr__.

- sbi/utils/pyroutils.py
- tests/pyroutils_test.py
Adds pyro utils to allow automatic transformation of variables. 
See `tests/pyroutils_test.py` for an example using a multivariate box uniform prior.
> Add pyro utils for transforms

- sbi/inference/__init__.py
- sbi/inference/abc/abc_base.py
- sbi/inference/abc/mcabc.py
- sbi/inference/abc/smcabc.py
- tests/abc_test.py
They will use a similar API as current `sbi` methods and return an empirical distribution as posterior. 
TODO:
> add abc methods to sbi.

- sbi/inference/base.py
- sbi/inference/posterior.py
- sbi/inference/snle/snle_a.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_b.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- sbi/utils/torchutils.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- accept only string "cpu" or "gpu" as device `kwarg`, "cpu" as default.
- depending of device string set device globally via torch default tensor type
- raise warning when "gpu" is used.
- rename `batch_size` in train methdos to `training_batch_size` to avoid confusion with `simulation_batch_size` and `batch_size` used in more general contexts.
- add missing usage of `device` in `SNRE`
closes #251 
relates to #257
> Fix device kwarg

- docs/docs/tutorial/markdown_files/03_flexible_interface.md
- docs/docs/tutorial/notebooks/03_flexible_interface.ipynb
- sbi/inference/posterior.py
- sbi/inference/snle/snle_a.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_b.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- sbi/neural_nets/classifier.py
- sbi/neural_nets/flow.py
- sbi/neural_nets/mdn.py
- sbi/utils/__init__.py
- sbi/utils/get_nn_models.py
- sbi/utils/sbiutils.py
- sbi/utils/torchutils.py
- tests/linearGaussian_snpe_test.py
Big refactor in order to address https://github.com/mackelab/sbi/issues/216. Help with this big PR is highly appreciated. It's not thoroughly tested yet (some tests might still fail), but the PR is ready for a first round of feedback
Core changes:
- Z-scoring of both, theta and x, now possible for all methods
- Delayed neural network creation till training data from round 0 is available
- Training data is passed to a function that builds the neural network. This way, shape inference and z-scoring can be handled inside the builder function
- Introduced a new module, `sbi.neural_nets` holding network builder functions
- No longer storing a deep copy of the initial posterior but calling the build function again if retrain from scratch is requested
Open questions:
- Please have a look at the …
> Z-scoring for all algorithms, refactor neural network creation

- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/user_input/user_input_checks.py
- sbi/utils/__init__.py
- tests/user_input_checks_test.py
A quick check on the `denisty_estimator` argument passed by the user. 
Passing a density estimator directly, e.g., a `nn.Module`, sounds intuitive given the name of the argument, but it results in an uninformative error. One has to pass a function returning a `nn.Module` instead. 
With this PR we add a small check on the `density_estimator` arg to give an informative error message.
> add check for density estimator arg.

- sbi/inference/base.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_base.py
- sbi/utils/__init__.py
- sbi/utils/sbiutils.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
We should support users that provide external data. Importantly, this should also be possible in multiple round inference (e.g. the user could run simulations on the cluster and inference on another computer), see #163 
For single round:
```
infer = SNPE(simulator, prior)
posterior = infer(num_round=1, num_simulations=0, external_data=(theta,x))
```
For multi-round, one can then do the following (not sure if I will implement this in this PR, but this would be the idea):
```
posterior_r2 = infer.continue(num_rounds=1, num_simulations=0, external_data=(theta2, x2), simulations_from_prior=False)
```
Here, the `simulations_from_prior` argument tells the inference algorithm whether the new simulations came from the latest posterior or from the prior. E.g. SNPE-B needs this information to use …
> Provide external data

- sbi/inference/posterior.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snre_test.py
I realised that we currently lack the possibility change MCMC default parameters for inference. 
This PR takes inspiration from Ole's PR (https://github.com/mackelab/sbi/pull/262) and adds getters and setters for MCMC method and MCMC parameters as well. The changes proposed in https://github.com/mackelab/sbi/pull/262 are subsumed in this one. 
Looking forward to feedback! I hope to merge this soon since I need to run MCMC with multiple chains and custom init for experiments.
> Setters for all things MCMC

- sbi/inference/posterior.py
- sbi/inference/snle/snle_a.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
This PR:
- adds `mcmc_parameters` to init methods of inference methods
- fixes a bug in which `log_weights` were not detached from graph when using `sir` init strategy for MCMC 
Will merge upon one review and release as `v0.10.1`.
> MCMC parameters to init of inference classes

- CHANGELOG.md
- sbi/inference/posterior.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
1) Warning for unnormalized log_prob was raised for SNRE_A but should be for SNRE_B
2) fixed constant log_prob of SNRE, see #275 
3) Reduced allowed threshold for DKL (old value had been picked for 3D example and a different likelihood).
Feel free to merge.
> fixed log_prob bug in snre

- CHANGELOG.md
- docs/docs/reference.md
- sbi/inference/base.py
- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/posterior.py
- sbi/inference/posteriors/snle_posterior.py
- sbi/inference/posteriors/snpe_posterior.py
- sbi/inference/posteriors/snre_posterior.py
- sbi/inference/snle/snle_a.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- sbi/types.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/test_utils.py
Tackles #214 
- child classes for snpe, snle, and snre posteriors.
- `log_prob()` and `sample()` now exist in the child classes, e.g. in `SNPE_Posterior`.
- docstrings of the posterior classes are now much more focused for the specific method.
- there is a new method in `base_posterior.NeuralPosterior` called `_prepare_theta_and_x_for_log_prob_()`. Do you think we need it or should we just copy the code to each of the child classes?
> Subclassing posterior

- CHANGELOG.md
- docs/docs/reference.md
- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/likelihood_based_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- tests/test_utils.py
Children have to implement `.sample()` and `.log_prob()`. Future methods might not allow to evaluate `log_prob()`, but I think it is good practice that these methods still implement a `.log_prob()` function which just raises an error.
- DirectPosterior
- LikelihoodBasedPosterior
- RatioBasedPosterior
str now also prints a `purpose` which can be either correcting leakage or doing mcmc.
> Additions to posterior refactoring (see #283)

- CHANGELOG.md
- docs/README.md
- docs/docs/faq.md
- docs/docs/faq/question_01.md
- docs/docs/faq/question_02.md
- docs/docs/install.md
- docs/mkdocs.yml
Seeded an FAQ for the website.
We could also add each of the questions to `nav`, but I think this would make the dropdown menu look quite ugly because of the long titles of the questions.
This is what it looks like:
And after clicking on one of the questions...
> Adding an FAQ section to website

- CHANGELOG.md
- sbi/neural_nets/classifier.py
- sbi/neural_nets/flow.py
- sbi/neural_nets/mdn.py
- sbi/utils/get_nn_models.py
Fixes #298 
We introduced `**kwargs` e.g. to `posterior_nn` [here](https://github.com/mackelab/sbi/blob/7c56cc210f226839bf91d037ccd258a733096de5/sbi/utils/get_nn_models.py#L48), which hides e.g. the `embedding_net` from the API reference.
The arguments to the functions are now explicit. We post-hoc rebuild the dictionary to avoid having to pass everything to each density estimator. If a specific `kwarg` does not apply to a specific density estimator, it is simply used up in the `**kwargs` of the build function and not used. For example, `build_mdn` will not have an argument `num_transforms` -> will be in `**kwargs`.
It is in theory possible to get all variables into a `dict` without having to retype the variable names (see [here](https://stackoverflow.com/questions/3972872/python-variables …
> Neural net creation documentation

- CHANGELOG.md
- docs/docs/faq/question_01.md
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/neural_nets/flow.py
- sbi/utils/__init__.py
- sbi/utils/get_nn_models.py
- sbi/utils/sbiutils.py
- sbi/utils/torchutils.py
- tests/linearGaussian_snpe_test.py
This will implement the non-atomic APT loss. The loss can be used if the density estimator is a Mixture of Gaussians. It does not have leakage issues (as atomic APT).
1D-cases are not yet covered because `mdn` have a `log_prob` error. This has been addressed but is not yet on PyPI.
> Non-atomic APT Loss

- sbi/inference/posteriors/direct_posterior.py
- sbi/utils/sbiutils.py
In multi-round SNPE, when the user called `log_prob()`, but the posterior had high leakage, the following happened:
- try estimating normalizing constant from 10000 posterior samples
- but high leakage
- hence a warning was raised that one should switch to `sample_with_mcmc=True`, which is not applicable for `log_prob`.
Now:
Different warning in this case.
> New warning leakage in log_prob()

- CHANGELOG.md
- sbi/inference/posteriors/base_posterior.py
- sbi/user_input/user_input_checks.py
- sbi/utils/sbiutils.py
- tests/multidimensional_x_test.py
Previously, the warning about multi-D `x` was raised when an `x_o` was passed, i.e., only during evaluation or sampling.
This PR changes the warning and raises as soon as one can infer the shape of `x`, i.e., after simulating. 
It also changes the search for invalid `x` and one assert to allow for multi-D in inference. Seems to work just fine. 
closes #333 
closes #332
> allow multiD x with appropriate embedding, add warning.

- CHANGELOG.md
- sbi/inference/snre/snre_base.py
- sbi/utils/sbiutils.py
Fixes a bug with `clamp_and_warn` not overriding `num_atoms` for SNRE and the warning message itself
> Fix clamp_and_warn

- CHANGELOG.md
- sbi/inference/posteriors/base_posterior.py
- setup.py
For context, see: https://github.com/mackelab/sbi/pull/288, https://github.com/mackelab/sbi/issues/286
While the bug was fixed in Pyro, no new Pyro version has been released yet. This PR explicitly passes `transforms={}` to Pyro, which allows using `1.4.0`.
> Pyro compatibility

- sbi/utils/sbiutils.py
This will hopefully speed up rejection sampling from the posterior in case of leakage. 
I moved the sampling and sample rejection to a separate function to reduce code repetition.
> batch size for posterior rejection sampling.

- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/likelihood_based_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/mcmc/init_strategy.py
Changes numpy potential functions to allow vectorized evaluations. The SIR init strategy is adapted to make use of the speedup.
Will merge upon 1 approving review
> Allow vectorized evaluation of numpy potentials

- sbi/inference/posteriors/base_posterior.py
- sbi/mcmc/__init__.py
- sbi/mcmc/slice_numpy_vectorized.py
- tests/linearGaussian_snle_test.py
- tests/mcmc_test.py
Adds vectorized version of numpy slice sampler which allows parallel log prob evaluations across all chains, making use of #341. This enables tremendous speed-ups for algorithms that use MCMC. 
All seems to work, and ready to be merged from my side. However, I would wait till we have used it internally for a longer time before making it the default choice.
> Vectorized slice sampler

- CHANGELOG.md
- sbi/inference/posteriors/base_posterior.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/mcmc/__init__.py
- sbi/mcmc/init_strategy.py
While `latest_sample` was implemented, it was transferred from the proposal distribution to the posterior object returned by inference which made it impossible to be used. This is addressed in this PR.
> Allow continuation of MCMC chains when using latest_sample

- sbi/utils/get_nn_models.py
In SNRE, the semantics of `x` and `theta` were swapped when building the net. When the classifier is used, thetas concatenated with xs are passed as input. During building, this was swapped, so that z-scoring wasn't performed as intended.
> Fixes init of SNRE classifier network by swapping pilot batches

- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/user_input/user_input_checks.py
- sbi/utils/__init__.py
- sbi/utils/sbiutils.py
- tests/multidimensional_x_test.py
- add assert against multi D `x` for SNPE and SNRE
- catch `RuntimeError` and give debug hint for multi D `x` without proper embedding net in SNPE
- small fix in user inputs
closes #351 
closes #357 
relates to #360
> fix warnings for multi D x

- docs/docs/index.md
I believe the `simulator` and `prior` arguments to `infer` are swapped in the example from the home page. Cheers!
> Fixing call to `infer` in the first snippet of the home page

- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- tests/multidimensional_x_test.py
quick fix for the `numpy` mcmc samplers: the repeat for `x` needs an `arg=1` for each non-batch dimension of `x`. 
closes #374
> fix np mcmc by repeating x on all axes, #374.

- sbi/inference/posteriors/base_posterior.py
- sbi/mcmc/slice_numpy.py
- pass `show_progress_bar` as verbose arg to `slice_np` to avoid showing pbars all the time.
> refactor np mcmc, pass verbose arg.

- sbi/inference/base.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
to better analyse training performance and convergence we were lacking the validation log probs for each epoch. We were only logging the single best validation log prob across all epochs, for each round. 
This PR adds a trace of validation log probs across all epochs and rounds that can be inspected using `tensorboard`.
> logging of validation logprobs for each epoch.

- CHANGELOG.md
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/utils/__init__.py
- sbi/utils/restriction_estimator.py
- tests/inference_with_NaN_simulator_test.py
Code for the rejection classifier, originally suggested in Lueckmann, Goncalves et al 2017
A classifier is trained to distinguish parameters that produce "bad" simulation outputs (e.g. NaN summary stats) from the ones that produce "valid" simulation outputs. Once the classifier is trained, we use it to reject prior samples before simulating them.
We call the space of parameters that are accepted by the classifier the `RestrictedPrior`.
We use a hard threshold for the classifier and allow 0.0% false negatives (by default), so we can use the `RestrictedPrior` as proposal and it still converges to the true posterior (without correction factors).
```python
from sbi.inference import SNPE
from sbi.utils import RestrictionEstimator
restriction_estimator = RestrictionEstimator(prior=prior) …
```
> Rejection estimator to deal with NaN

- CHANGELOG.md
- sbi/utils/conditional_density.py
- tests/sbiutils_test.py
Fixes the issue reported in #403. The issue arises only when the `limits` are not symmetric around the origin **and** are not the same in each dimension. Because of this, the issue slipped through the tests.
This PR is a one-line fix, and it also updates tests so that such a problem would be caught in the future.
`torch.flip()` is needed because `meshgrid` generates axes that are transposed to the probability matrix that we generate with `torch.repeat()` and `torch.repeat_interleave()`. See:
- for meshgrid: https://github.com/mackelab/sbi/blob/1534cff14dee1c1e0013ad22b2f931eb7424bb42/sbi/utils/conditional_density.py#L250
- for the probability axes: https://github.com/mackelab/sbi/blob/1534cff14dee1c1e0013ad22b2f931eb7424bb42/sbi/utils/conditional_density.py#L66-L70
By flipping the limits, …
> fixup for conditional correlation matrix, #403

- CHANGELOG.md
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- tests/inference_with_NaN_simulator_test.py
We currently infer the mean and std of our data from all datapoints, including the validation set.
It is good practice to consider the mean and std as model parameters and therefore use only the training data to identify the mean and std.
See #393
> z-score only using training data

- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/inference/snre/snre_base.py
- sbi/neural_nets/classifier.py
- sbi/utils/get_nn_models.py
- tests/multidimensional_x_test.py
This PR fixes the issue reported in https://github.com/mackelab/sbi/issues/424 (thank you @adittmann). 
It also changes the code such that SNRE passes inputs as lists. Previously, inputs were concatenated. With lists, it becomes possible to e.g. use a convolutional network for embedding xs and no embedding for thetas.
closes #424 
closes #360
> SNRE embedding fixes

- CHANGELOG.md
- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/likelihood_based_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/utils/__init__.py
- sbi/utils/sbiutils.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
This PR implements the Maximum-a-posteriori (MAP) estimate for SNPE, SNLE, SNRE. It is obtained by gradient ascent from some starting locations (usually sampled from the posterior).
See #306 and #276 and #392
```
posterior = inference.build_posterior()
map_ = posterior.map(x=xo)
```
While the optimization is running, we print:
When interrupting:
for a 3D Gaussian, it is around 30 seconds. For the 31D STG, it's at 100 seconds with default parameters.
- relatively high interrun-variability.
- black-box algorithm, I have no idea what is happening there.
- one more dependency
- why not use gradients if we have them?
We could still revert to `cma` though, I will not squash the commit.
- for SNPE: we would obtain the likelihood by dividing the posterior by the prior. However, if the prior drops …
> MAP estimate

- .github/workflows/tests.yml
We ran slow tests at every commit. This is because:
```
pytest -m "not slow" -m "not gpu" tests/
```
will only consider the last argument passed to `-m`. Thus, only tests that used gpu were ignored, but slow tests were still run. The correct syntax is described here: https://github.com/pytest-dev/pytest/issues/6142
> Do not run slow tests

- CHANGELOG.md
- sbi/inference/base.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/utils/sbiutils.py
- tests/abc_test.py
- tests/inference_with_NaN_simulator_test.py
- tests/test_utils.py
Closes #409 
Two options:
1) Always check `if prior is not None:` and build special cases for it
2) If `prior=None` is passed, then build an [empirical distribution](http://docs.pyro.ai/en/0.2.1-release/_modules/pyro/distributions/empirical.html) out of samples passed to `append_simulations`.
I implemented option (1) in the first commit. I kind of prefer option (2) though, so I implemented it in the second commit and we can revert to option (1) if we have trouble with (2).
> Make prior optional for SNPE

- CHANGELOG.md
- docs/docs/faq.md
- docs/docs/faq/question_05.md
- sbi/inference/posteriors/base_posterior.py
- tests/inference_with_NaN_simulator_test.py
For posteriors saved after `sbi v0.13.0`, we now support loading them under newer versions. Saving and loading should be done with pickle. If we add new attributes to the posterior class, we have to add them to the `__setstate__` method.
Fixes #386
> Pickling the posterior across sbi versions

- sbi/simulators/simutils.py
- sbi/utils/user_input_checks.py
- tests/simulator_utils_test.py
- tests/user_input_checks_test.py
Up to now, when a user passed a simulator that wasn't able to handle batches of theta, we wrapped it to still return a batch dimension.
The wrapped simulator still was simulating just a single theta though.
When using multiprocessing, spawning workers for every single theta can create a lot of overhead, especially when single simulations are cheap.
With this PR, we are wrapping the un-batched user-simulator into a simulator that just loops over a batch of thetas. As a consequence one can now set sim_batch_size>1 in simulate_in_batches and reduce overhead to a minimum. This can result in 10x speed up for some problems!
> add loop simulator to always enable sim batch size.

- CHANGELOG.md
- docs/docs/faq.md
- docs/docs/faq/question_05.md
- docs/docs/faq/question_06.md
- docs/docs/reference.md
- sbi/inference/snle/snle_a.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- tests/linearGaussian_snpe_test.py
Fixes #309 
This PR introduces the argument `resume_training` to `.train()`. If `True`, the split between train and validation set, the optimizer,  the number of epochs, and the best validation log-prob will be restored from the last time `.train()` was called.
Syntax is:
```python
inference = SNPE(prior=prior)
inference = inference.append_simulations(theta, x)
inference.train(max_num_epochs=300)  # Pick `max_num_epochs` such that it does not exceed the runtime.
inference.train(resume_training=True, max_num_epochs=600)  # Run epochs 301 until 600.
posterior = inference.build_posterior()
```
Using the above syntax will be identical up to seeding to:
```python
inference = SNPE(prior=prior)
_ = inference.append_simulations(theta, x).train()
posterior = inference.build_posterior()
```
> Allow to stop and resume neural network training

- CHANGELOG.md
- sbi/utils/sbiutils.py
- tests/inference_with_NaN_simulator_test.py
Quick bugfix, it always warned because the `(1 - duplicate_tolerance)` was in the wrong place.
> Fix bug for warning on z-score

- CHANGELOG.md
- sbi/neural_nets/flow.py
- sbi/utils/get_nn_models.py
In 1D, we have...
1) no conditioner
2) no "alternating masks" between layers
3) Due to no alternation, we also need only num_transforms=1. Warn if num_transforms > 1
In the second commit, we allow for `num_bins` to be settable in `posterior_nn` and `likelihood_nn`. I have found improved performance as I increased `num_bins` in several problems.
> Allow to estimate 1D densities with NSF

- sbi/inference/snpe/snpe_base.py
- sbi/utils/user_input_checks.py
- tests/user_input_checks_test.py
This unittest documents a "bug" in `utils/user_input_checks.py` that happens only when using the GPU but not on the CPU for me.
I can submit a fix, if needed.
Some details about my environment:
```
$ uname -a
Linux ga001.cluster 3.10.0-1160.6.1.el7.x86_64
$ python -V
Python 3.8.0
$ python -c 'import torch;print(torch.__version__)'
1.7.1
$ python -c 'import sbi;print(sbi.__version__)'
0.14.2
$ nvcc --version
#...
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```
> testing assumptions of type checks

- sbi/inference/snle/snle_a.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
Added dataloader_kwargs parameter to snle_a, snre_a, snre_b and snpe_c. These dataloader_kwargs are used to create the train and val dataloaders in snpe_base, snre_base and snle_base
@janfb I closed the previous MR, merged the current sbi main into my fork, and put the dataloader_kwargs related changes. I have avoided any formatting changes (that caused problems last time) - let me know if this looks ok :) 
Closing #415
>  2nd try: Adding the ability to pass dataloader related kwargs in SNPE, SNRE and SNLE

- sbi/inference/base.py
- sbi/inference/snle/snle_a.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- tests/base_test.py
moving creation of data loader to `base.py` to reduce code repetition for creating the data loader in each inference base class separately. 
see #415 and #445 
TODO:
> move dataloading to base class.

- sbi/inference/posteriors/base_posterior.py
- sbi/utils/__init__.py
- sbi/utils/sbiutils.py
- sbi/utils/torchutils.py
- sbi/utils/user_input_checks.py
This fixes issues with torch version 1.8.0
1) if a torch distribution is passed, ensure that it has `validate_args=False`. This will allow calling `log_prob()` even when the samples are outside of the support.
2) Also ensure `validate_args=False` for `BoxUniform` and `PytorchReturnTypeWrapper`
3) whenever we check whether samples are inside the support: checks whether the `distribution` has a `support` attribute (as is the case for any `torch.distribution`). If it does not, it evaluates the log-probabilty and returns whether it is finite or not (this hanldes e.g. `NeuralPosterior`). Only checking whether the log-probabilty is not `-inf` should also work due to steps 1) and 2), but we are on the save side if the user does not run the prior through `prepare_for_sbi()`.
Note: for the core …
> Fix for torch v1.8.0

- sbi/utils/conditional_density.py
- sbi/utils/plot.py
Quick bug-fix. It was warning even when doing the correct import:
```
from sbi.analysis import conditional_pairplot, conditional_corrcoeff
```
> Remove deprecation warning when correctly import conditional_pairplot

- sbi/inference/posteriors/direct_posterior.py
Hi,
based on the leakage correction message, I wanted to reduce the number of samples to be drawn. However, I couldn't find a way to forward the arguments to `DirectPosterior.leakage_correction()`, which is only used at this place. Maybe I am overlooking something...
Bests,
Fabio
> Expose leakage_correction() args to log_prob() of DirectPosterior

- sbi/inference/posteriors/base_posterior.py
`posterior.map()` prints the progress bar regardless of setting, so I put in a check
> show_progress_bars=False was not turning off the display, now modified

- sbi/utils/user_input_checks_utils.py
- tests/user_input_checks_test.py
Since the new PyTorch version distributions have the `support` property. We are using this property, e.g., when checking that the posterior samples lie within the prior support. 
For priors that are independent we implemented a new distribution `MultipleIndependent(Distribution)` to sample and evaluate a sequence of independent PyTorch distributions. However, this new class doesn't implement the `support` property yet and this results in an error when using this joint prior feature. 
This PR does that by implementing a new `Constraint` class that holds a list of independent `Constraints`, one for each independent prior distribution, and checks the support for each of them, taking into account the corresponding event dimension.
> add independent constraints for support attribute.

- sbi/utils/sbiutils.py
- sbi/utils/user_input_checks.py
- sbi/utils/user_input_checks_utils.py
- tests/linearGaussian_snpe_test.py
When the prior is wrapped and does not implement the abstract property `support`, checking for this attribute will result in a `NotImplementedError`. 
This is a quick fix that catches this error and instead performs the support check by evaluating the samples. 
Open for discussing for a better / more general fix. 
closes #463
> fix error handling in support check.

- CHANGELOG.md
- sbi/analysis/conditional_density.py
- sbi/neural_nets/flow.py
- sbi/utils/conditional_density.py
Two independent things in these two commits:
1) the first commit adds the option to return the raw log-prob in `eval_conditional_density` (not documented in changelog because it's very specific)
2) bug fix: `num_bins` had not been used.
> Num bins fix

- sbi/inference/posteriors/direct_posterior.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/test_utils.py
in the context of `posterior.map()` we are still using `torch.isfinite(prior.log_prob(theta))` to check whether `theta` is in the support. This can result in `value must be in support` error in `PyTorch`.
This PR uses `within_support` instead to fix this.
> within_prior instead of log_prob for support check.

- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/inference/snpe/snpe_base.py
- tests/linearGaussian_snre_test.py
- tests/multidimensional_x_test.py
- tests/test_utils.py
Analog to SNLE: rewrite log ratios to take the sum over the batch dimension of `x`, assuming it to contain `iid` trials. 
Adapt `log_prob` and potential functions accordingly to then use MCMC to infer the posterior given `iid` x.
> snre support for inference given batch of iid x

- sbi/inference/snpe/snpe_a.py
In #478, I said that a default value for `component_perturbation` of `1e-2` is way larger than in the original paper.  Well, after doing some experiments with SNPE-A, I noticed that for small values in the rage of [1e-6, 1e-4] the perturbation is (at least in the cases I looked at) too small. Thus, the x = 2,...,10 components stayed right where the one component after running Algorithm 1 ended up. Therefore I suggest raising this value.
Moreover, I noticed that the "optimal" `component_perturbation``value also depended on the number of components. As a rule of thumb, more components required a bigger value. But please take this information with a grain of salt.
> Changed the default value of component_perturbation

- sbi/inference/snpe/snpe_a.py
I suggest to remove the optional correction of the precision matrix for 2 reasons:
1. Forcefully making a matrix positive definite is hacky, and
2. This option was only useful for the evil case where SNPE-A yields a denisty esimator with lower precision than the proposal prior. Hoewever, if this is the case, rejection sampling from MoG typically "fails" (super high rejection rates). Since MCMC sampling is disabled for SNPE-A (makes sense), I think it is best to let the attept fail and signal the user to try different params or a different random seed  :upside_down_face:
> Removed the optional correction of the precision matrix

- .vscode/settings.json
- sbi/mcmc/init_strategy.py
to avoid overflow when moving to `exp` space. 
keep the normalisation in `exp` space below because the norm could change in case there are still some nans.
> norm sir weights in logspace.

- sbi/mcmc/init_strategy.py
- tests/linearGaussian_snle_test.py
small fix for SIR init: `logsumexp` actually requires the dim arg.
> add required dim arg to logsumexp.

- docs/docs/faq/question_04.md
- sbi/analysis/conditional_density.py
- sbi/inference/base.py
- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/likelihood_based_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/inference/snpe/snpe_a.py
- sbi/mcmc/slice.py
- sbi/utils/metrics.py
- sbi/utils/sbiutils.py
- sbi/utils/torchutils.py
- sbi/utils/user_input_checks_utils.py
- tests/abc_test.py
- tests/inference_on_device_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snre_test.py
- tests/mcmc_test.py
- tests/user_input_checks_test.py
Relates to #515 
Up to now we assumed the prior live on the `cpu` and we moved samples to `.cpu()` whenever combining `log_probs` from the `prior` and the `net`. 
This PR now allows the prior to live on the `GPU`, and it `asserts` that the prior lives on the same device as the passed `device` for training
Pro: we don't need to move to `.cpu()` all the time
Con: 
- all the `numpy` based MCMC methods naturally happen on the `cpu`. when evaluating the `theta` on the prior, we now have to move it to the `prior` device (instead of doing `net.logprob(theta).cpu()`)
- now the user will get an `AssertionError` when the prior was not on initialised on the `device`. This was not the case before. **Alternatively**, we could introduce or deduce `prior_device` and take care of moving things around …
> Allow prior on gpu

- CHANGELOG.md
- sbi/analysis/sensitivity_analysis.py
- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/likelihood_based_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/mcmc/init_strategy.py
- sbi/utils/__init__.py
- sbi/utils/plot.py
- sbi/utils/sbiutils.py
- tests/inference_on_device_test.py
- tests/linearGaussian_snpe_test.py
- tests/sbiutils_test.py
- tutorials/07_conditional_distributions.ipynb
This PR does the following:
- Allow to `scatter` in `pairplot` also on the diagonal (so far only on the upper diag)
- fix for `sample_conditional()` (was broken after #487)
- add `_sample_with()` to `__set_state__()` (old posteriors could not be loaded anymore after #487)
- Small fix for `ActiveSubspace` which had raised a warning due to newer torch version.
- Do MCMC in unconstrained and z-scored space.
Todo:
> Do MCMC in unconstrained space

- sbi/inference/abc/mcabc.py
- sbi/inference/abc/smcabc.py
- sbi/types.py
- sbi/utils/__init__.py
- sbi/utils/kde.py
- sbi/utils/sbiutils.py
- tests/abc_test.py
see #523 for details. 
`ABC` methods now return either the final set of accepted particles (and a summary `dict` containing the corresponding distances, data and weights), or a KDE object fitted on those particles (and the summary `dict`). The KDE object can be used for sampling and evaluating the approximate posterior. 
closes #523
> let abc return particles or kde, adapt tests.

- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/likelihood_based_posterior.py
- sbi/inference/posteriors/ratio_based_posterior.py
- sbi/inference/snle/snle_a.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_a.py
- sbi/inference/snre/snre_b.py
- sbi/utils/torchutils.py
ensure the device string is `"cpu"` or `"cuda{:*}"` and change docstrings accordingly. 
see #533
> improve docs for device handling.

- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
When passing a custom density estimator to the build_posterior function of SNPE, I ran into **AttributeError: 'torch.device' object has no attribute 'startswith'** (see traceback below).
This seems to be caused by the else case of `build_posterior( )` in snpe_base.py, snle_base.py and snre_base.py, where the device is determined from the density estimator's parameters and becomes a torch.device object instead of a string. Finally, `process_device(device, prior)` in torchutils.py causes an assertion error, as `startswith()` is a string-specific function.
The error can be reproduced by running https://github.com/mackelab/sbi/blob/main/tutorials/02_flexible_interface.ipynb with either SNPE, SNLE or SNRE. 
I fixed it by converting the torch.device object into a string.
```
AttributeError: …
```
> Fix device string handling if density estimator is provided

- sbi/inference/abc/mcabc.py
- sbi/inference/abc/smcabc.py
- sbi/utils/kde.py
- tests/abc_test.py
minor fixes for kwargs usage for KDE in ABS methods. 
I would merge with one OK and then create a new release on which `sbibm` will depend in the future.
> fix abc kde kwarg handling, adapt tests.

- CHANGELOG.md
- sbi/__version__.py
- sbi/inference/abc/smcabc.py
- sbi/utils/kde.py
- tests/abc_test.py
- tests/sbiutils_test.py
TL;DL always wrap with transforms as `IndependentTransform` to have parameter dimension as event dimension. 
transforms need an event dimensions such that when `log_prob` is called with a tensor shaped `(batch, parameter_dims)` a tensor shaped `(batch,)` is returned, instead of a tensor with a log_prob for every parameter dimension separately. 
To do this we need to wrap the transforms with `IndependentTransform` to reinterpret the batch dim as event dim (like it is done for the `BoxUniform` prior). 
This was not happening for the default case in `get_kde` where no transform is passed and an `identity_transform` is used.
> use independent transform to wrap event dims. formatting

- sbi/neural_nets/flow.py
- tutorials/11_sampler_interface.ipynb
refactoring the usage of `nsf`. Importantly, in case of a one-dimensional `x` we are currently warning that in this case it wouldn't help to have more than one transform. 
However, I think it still makes sense to have multiple transforms. In this case the spline parameters are learned from the conditioning variables only, because there is no "other" dimension in `x` to learn from. But we can still use multiple transforms to stack conditioners and get more flexibility. 
Maybe I am missing something here? But in my current view this makes sense and we should remove the warning.
> Refactor nsf

- sbi/inference/posteriors/mcmc_posterior.py
See #567 
@jan-matthis liked the issue, so I guess he agrees with using SIR as default?
> Set SIR as default init_strategy for MCMC

- sbi/inference/posteriors/mcmc_posterior.py
See #547 
I reproduced the issue on mac and linux. The fix works for both macbook pro (2013) and ubuntu.
> Change mp context to allow for multi-chain MCMC (pyro)

- docs/docs/faq/question_07.md
Hey @janfb, I made a first FAQ draft. to address #581, #582. Should I change anything?
I also tried @michaeldeistler suggestion of adding `.support()` to CustomPrior as mentioned in #581, but the sbi wrapper does not play well with `pytorch.distribution.distribution`, see output below.
```
<class 'sbi.utils.user_input_checks_utils.CustomPytorchWrapper'> does not define `arg_constraints`. Please set `arg_constraints = {}` or initialize the distribution with `validate_args=False` to turn off validation.
```
I therefore did not include that as a temporary fix for users below 0.17.2.
> first draft of FAQ to address #581 and #582

- .gitignore
- sbi/inference/base.py
- sbi/utils/__init__.py
- sbi/utils/tensorboard_output.py
- tests/plot_test.py
I added extraction for any tensorboard data and basic plotting for any scalar tensorboard data for diagnostics.
**Usage examples**
1) Plotting tensorboard data from inference object. The warning prompt is to support the user to start tensorboard for interactive visualization, as well as with hints on the valid tags. 
2) Plotting tensorboard data from Path returned by `sbi.utils.list_all_logs(inference)`, to be able to iterate over log directories of past runs directly.
Note: For possible future extensions, I wrote `_get_event_data_from_log_dir`  to parse the tensorboard data into a convenient tabular format.
> Plot functions for tensorboard data

- tests/abc_test.py
ABC tests are currently failing due to C2ST=0.60003
I reduced the number of simulations, they work now
> Reduced number of simulations for ABC tests

- sbi/analysis/sensitivity_analysis.py
- sbi/inference/base.py
- sbi/utils/sbiutils.py
This allows using the progress statement on google colab #330 
Note that, after this change, the progress statement is indented by one character:
> Fix progressbars for gcolab

- docs/docs/faq/question_07.md
- sbi/utils/__init__.py
- sbi/utils/sbiutils.py
- sbi/utils/user_input_checks.py
- sbi/utils/user_input_checks_utils.py
- tests/user_input_checks_test.py
- add `validate_args` and `support` to the custom prior wrapper.
- allow the user to pass upper and lower bound kwargs for priors with bounded support.
fixes #581 
relates to #595
> Fix custom prior support

- sbi/inference/base.py
closes #576 
slow tests where failing because we were checking for non-unique `x` without excluding invalid `x`. This is fixed here.
> check effect of z-scoring only on valid data, #576.

- sbi/utils/sbiutils.py
- sbi/utils/user_input_checks.py
- sbi/utils/user_input_checks_utils.py
- tests/sbiutils_test.py
- tests/transforms_test.py
- tests/user_input_checks_test.py
This PR allows to infer the `transform` for priors that were provided as `MultipleIndependentDistributions`.
In addition, it allows inferring the transform for **any** bounded distribution (not just interval constraints)
> Allow MCMC transforms for MultipleIndependentConstraints prior

- sbi/analysis/plot.py
- sbi/neural_nets/classifier.py
- sbi/neural_nets/flow.py
- sbi/neural_nets/mdn.py
- sbi/utils/__init__.py
- sbi/utils/get_nn_models.py
- sbi/utils/restriction_estimator.py
- sbi/utils/sbiutils.py
- tests/linearGaussian_snpe_test.py
- tests/multidimensional_x_test.py
- tests/sbiutils_test.py
`standardizing_net()` and `standardizing_transform()` now both have options to perform z-scoring for structured data, i.e., to compute `mean` and `std` for each sample first, then taking the global mean to be used for z-scoring the batch (instead of z-scoring each dimension independently): 
`x_mean = torch.mean(x)`
`x_std = torch.mean(torch.std(x, dim=1))`
Re: #570
> added z-scoring method for structured data (e.g., time series)

- sbi/utils/metrics.py
- tests/metrics_test.py
I wanted to understand the ins and outs of `c2st` better. I am putting this here. potentially my code can help to improve it. Also, `c2st` is untested currently.
> Refactor c2st and adding a unit test for metrics

- docs/docs/faq/question_05.md
- sbi/inference/base.py
Resolves #476 
Saving the inference object was always a bit messy. But `dill` used to work.
I just tried and could no longer save the inference object with dill. The workaround in this PR is to set the non-serializable objects to `None` before saving. This allows to save the inference object with `pickle`. These modifications lead to the following two changes in behaviour:
1) Retraining from scratch is not supported, i.e. `.train(..., retrain_from_scratch=True)` does not work after loading.
2) When the loaded object calls the `.train()` method, it generates a new tensorboard summary writer (instead of appending to the current one).
> Make inference object serializable

- sbi/analysis/plot.py
- sbi/samplers/mcmc/init_strategy.py
Before this PR, SIR cast the types twice: first from torch to numpy and then back to torch. Now it's fully based on torch. This also fixes the currently failing GPU tests.
> torch backend for SIR

- sbi/inference/base.py
- sbi/neural_nets/classifier.py
- sbi/neural_nets/flow.py
- sbi/neural_nets/mdn.py
- sbi/utils/torchutils.py
- sbi/utils/user_input_checks.py
- tests/inference_on_device_test.py
- tests/user_input_checks_test.py
I think most of the issues encountered by users result from `device` strings processing and mismatch. I'm trying a bunch of error-prone combinations and trying to see how can those mismatch be catched and corrected.
For now I only tried very small changes.
2 (known) issues remain:
- prior device mismatch
- embedding net with custom density estimator mismatch
But both items do not expose any device attribute for now so maybe more invasive changes could be needed
> GPU device placement issues

- sbi/analysis/__init__.py
- sbi/analysis/plot.py
- tests/plot_test.py
I added a first set of plotting functions for SBC like I was using them so far. 
They are plotting the SBC results as empirical CDFs like suggested in the later figures in the Talts et al. paper, not as histograms. 
@psteinb feel free to comment, and to add purely histogram-based plots if you find them more appropriate. This is all open for discussion. 
fixing #588 
to do: 
If this is needed in `main` for completing the SBC tutorial, we can merge after a review from @michaeldeistler . Then we should move these todos to a separate issue.
> add sbc plotting funtions.

- sbi/analysis/sbc.py
- sbi/inference/base.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/samplers/rejection/rejection.py
- sbi/simulators/simutils.py
- sbi/utils/sbiutils.py
- tests/inference_on_device_test.py
- tests/multiprocessing_test.py
First of all, thanks for this great library!
I used it recently and I had to change a few things on my use case:
- Use an adaptive batch size for rejection sampling. When trying to get `1000` samples with rejection rate to `3%`, it can be quite frustrating to need to do a second full `1000` batch instead of sampling `100`. I propose a strategy that should not change to much the current behavior but simply reduce these edge cases.
- Setting grad to zero before returning/copying the model to avoid large memory consumption.
- Using negative number to set the `num_workers` parameter to compute simulations. When running experiments on heterogeneouse cluster, it is nice to be able to set the number of workers relative the number of CPUs available.
- A few clean up for some unused imports.
I did …
> FIX neg num_workers + adaptive rejction batch + reduce memory leak

- sbi/utils/restriction_estimator.py
- sbi/utils/sbiutils.py
- tests/inference_with_NaN_simulator_test.py
The `RestrictedPrior` was not originally meant to be passed as a `prior` to SNPE. But this has been requested in #640. Thus, we are allowing this with this PR. In order to do this, we add a `.log_prob()` method to the `RestrictedPrior`.
> Add `log_prob()` to RestrictedPrior

- CONTRIBUTING.md
- setup.py
- tests/abc_test.py
- tests/analysis_test.py
- tests/conftest.py
- tests/ensemble_test.py
- tests/inference_on_device_test.py
- tests/inference_with_NaN_simulator_test.py
- tests/linearGaussian_mdn_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/mcmc_slice_pyro/test_slice.py
- tests/mcmc_test.py
- tests/metrics_test.py
- tests/sbc_test.py
- tests/test_utils.py
- tests/vi_test.py
- remove `set_seed` args
- adapt two tests that were not seeded before to make them pass with seed
> autouse seed fixture in pytest to seed all tests. 

- sbi/samplers/mcmc/init_strategy.py
- tests/sbc_test.py
fixing #634 
not sure why exactly this failed only for the `MultipleIndependent` prior. Isn't the `sir` supposed to use the transformed potential in any case, i.e., isn't this a general bug? @michaeldeistler
> perform sir in untransformed space to fix #634.

- sbi/inference/posteriors/mcmc_posterior.py
- sbi/inference/posteriors/vi_posterior.py
- sbi/samplers/mcmc/slice_numpy.py
- tutorials/02_flexible_interface.ipynb
- tutorials/11_sampler_interface.ipynb
closes #662 
plus:
- tutorial notebooks contained example API in code cells that then throw an error when executed. I changed them to markdown. 
- fixes a bug with number of init params in parallel MCMC
- fixes pbar descriptions and switches for parallel MCMC and vectorized MCMC
> import tqdm from auto to fix pbars.

- tutorials/07_conditional_distributions.ipynb
This adds documentation for sampling the conditional posterior. I added it to the end of the already existing tutorial on [conditional distributions](https://www.mackelab.org/sbi/tutorial/07_conditional_distributions/)
> Tutorial for sampling the conditional

- docs/mkdocs.yml
I found our Tutorials to have become a bit messy. I added a new category `analysis`. I also moved the `flexible interface` and the `sampler interface` to `Introduction`. Let me know what you think of this.
> reorganize tutorials

- sbi/samplers/vi/vi_pyro_flows.py
- tests/vi_test.py
this adds a test showing a failure mode of VI: 
When sampling from a `VIPosterior` based on a `MultipleIndependent` prior there is a problem with the `theta_transform` and the `vi_pyro_flows`. I think it has to do with change in dimensionality from transformed to untransformed space, .e.g., it happens when calling `link_flow(torch.zeros(event_shape, device=device))` (see trace below). Potential problem: Why is this called with just the `event_shape` and not the entire `theta.shape`? 
track: 
```
sbi/inference/posteriors/vi_posterior.py:132: in __init__
self.set_q(q, parameters=parameters, modules=modules)
sbi/inference/posteriors/vi_posterior.py:230: in set_q
device=self._device,
sbi/samplers/vi/vi_pyro_flows.py:156: in build_fn
return _FLOW_BUILDERS[name](event_shape, link_flow, …
```
> vi failing with independent prior

- sbi/analysis/tensorboard_output.py
- sbi/inference/base.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- tests/abc_test.py
Refactoring of logging via summary writer: 
- remove old logging details
- add consistent and informative naming
- add documentation
closes #594
> Refactor logging with summary writer

- sbi/inference/posteriors/mcmc_posterior.py
- sbi/samplers/importance/sir.py
- sbi/samplers/mcmc/init_strategy.py
quick fix to actually use `init_strategy_num_candidates` in `sir`. 
However, I am not sure, how `init_strategy_num_candidates` relates to `sir_num_batches` and `sir_batch_size`. Previously, we used `init_strategy_num_candidates=sir_num_batches * sir_batch_size`, but this was replaced by the `oversampling factor right? @michaeldeistler can you clarify? 
https://github.com/mackelab/sbi/blob/ce389f8ce633985b8ea7cf96b1ea0001daac3dd5/sbi/samplers/importance/sir.py#L39-L40
> pass on sir kwargs to init method.

- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/potentials/posterior_based_potential.py
fixes #713 
Before this PR, the `DirectPosterior` was constructing a `theta_transform` from the prior support **by default** and used it for maybe calculating the MAP. This can cause issues if a custom prior has a funky support. 
This PR adds the `theta_transform = None` argument to the `DirectPosterior` top level so that users can pass an `IdentityTransform` to avoid the default construction of a transform to unconstrained space. If the argument is left `None` the support of the prior is used to construct a transform -- as before.
> make transform optional for DirectPosterior.

- sbi/inference/snpe/snpe_a.py
SNPE-A is always trained with Maximum-likelihood, so force_first_round_loss=True always.
> force_first_round_loss=True for SNPE-A

- sbi/inference/snpe/snpe_base.py
> allow gpu when using an empirical prior for SNPE

- sbi/inference/snpe/snpe_c.py
if one used, e.g., an `MCMCPosterior`, or simply a `torch.distributions.MultivariateNormal`, one would get an error that the propsals has no attribute `posterior_estimator`. This is fixed here.
Resolves #706
> allow more flexible proposals in atomic snpe-c

- CHANGELOG.md
- sbi/__version__.py
- sbi/inference/snpe/snpe_c.py
- setup.py
- tests/linearGaussian_snpe_test.py
fixes #733 
@michaeldeistler feel free to adapt and merge.
> add test, adapt error message.

- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/importance_posterior.py
- sbi/inference/posteriors/mcmc_posterior.py
- sbi/inference/posteriors/rejection_posterior.py
- sbi/inference/posteriors/vi_posterior.py
- sbi/inference/potentials/likelihood_based_potential.py
- sbi/inference/potentials/posterior_based_potential.py
- sbi/inference/potentials/ratio_based_potential.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/samplers/importance/sir.py
- sbi/utils/posterior_ensemble.py
- sbi/utils/potentialutils.py
- sbi/utils/restriction_estimator.py
- sbi/utils/sbiutils.py
the current API does not allow to **not** perform sampling in unconstrained space. 
In scenarios where one has already transformed parameters to unconstrained space, one workaround is to manually build potential functions and pass them to the posterior object. 
But it would be nice to enable this for `build_posterior` as well, as it offers more flexibility to switch between sampling methods etc. 
This PR exposes the `enable_transform` argument from `mcmc_transform` at the top level to allow this for all methods. 
Note: To keep things parallel for all three methods, this PR reverts #714, which enabled custom transforms for `NPE`.
> expose enable_transform for all methods.

- sbi/simulators/simutils.py
- sbi/utils/sbiutils.py
- tests/analysis_test.py
- tests/conftest.py
- tests/linearGaussian_snle_test.py
- tests/simulator_utils_test.py
introduces individual seeds for each workers to ensure reproducibility for parallel simulations.
fixes #758
> add seeding.

- docs/docs/faq/question_06.md
- docs/docs/index.md
- docs/mkdocs.yml
- sbi/analysis/sbc.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/samplers/__init__.py
- sbi/samplers/importance/sir.py
- sbi/samplers/rejection/rejection.py
- sbi/utils/__init__.py
- sbi/utils/restriction_estimator.py
- tests/inference_with_NaN_simulator_test.py
- tests/linearGaussian_snpe_test.py
- tests/save_and_load_test.py
- tests/sbc_test.py
- tutorials/11_sampler_interface.ipynb
- tutorials/13_diagnostics_simulation_based_calibration.ipynb
- tutorials/15_mcmc_diagnostics_with_arviz.ipynb
- tutorials/16_implemented_methods.ipynb
Renamed `rejection_sample_posterior_within_prior` to `accept_reject_sample` since it is more general than to sample the posterior within the prior.
```python
from sbi.inference import SNPE
from sbi.utils import get_density_thresholder, RestrictedPrior
inference = SNPE()
_ = inference.append_simulations(theta, x).train()
posterior = inference.build_posterior()
accept_reject_fn = get_density_thresholder(posterior, quantile=1e-4)
proposal = RestrictedPrior(prior, accept_reject_fn, sample_with="rejection")
```
```python
from sbi.analysis import run_sbc
ranks, dap_samples = run_sbc(theta, x, reduce_fns=posterior.log_prob)
```
> Implementation of TSNPE

- sbi/neural_nets/embedding_nets.py
- tests/embedding_net_test.py
failing test for 1D CNN embedding, see #750 
and a new implementation of the CNN embedding net including 1D and 2D convolution, and some input checks.
> 1d and 2d cnn embedding nets.

- sbi/utils/user_input_checks_utils.py
- tests/user_input_checks_test.py
see #774 
improves error messages. does not apply `process_prior` recursively on a passed list of custom priors to avoid circular imports.
> improve error handling for custom priors.

- sbi/utils/user_input_checks.py
- tests/embedding_net_test.py
- tests/user_input_checks_test.py
> improve handling of multi-d x in SNPE, adapt iid test.

- sbi/inference/snpe/snpe_base.py
This PR should address issues in the tests mentioned in #788. The `is_valid_x` index will be (maybe) copied to the correct device for `x` and `theta` before indexing. Thereby a runtime error is avoided.
> update the device for is_valid_x

- README.md
- docs/docs/index.md
- docs/docs/reference.md
- sbi/inference/__init__.py
- sbi/inference/snre/__init__.py
- sbi/inference/snre/bnre.py
- sbi/inference/snre/snre_base.py
- tests/linearGaussian_snre_test.py
- tutorials/16_implemented_methods.ipynb
Implement Balanced neural ratio estimation.
> Balanced neural ratio estimation

- .github/workflows/tests.yml
codecov v1 is deprecated, see codecov: https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1
> upgrade to codecov v3

- sbi/analysis/plot.py
- sbi/analysis/sbc.py
- tests/plot_test.py
- tests/sbc_test.py
- tests/test_utils.py
when creating the list of `reduce_fn`s for SBC, we need to index the columns of `theta`, not the rows. 
Addtionally, the local variable `i` will not bind to the corresponding `lambda` functions. 
I worked around that with an `eval` for now, but there is certainly a more elegant solution out there. 
closes #794
> fix sbc reduce funs, refactor plotting.

- README.md
- docs/docs/index.md
- docs/docs/reference.md
- sbi/inference/__init__.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/potentials/likelihood_based_potential.py
- sbi/inference/potentials/posterior_based_potential.py
- sbi/inference/potentials/ratio_based_potential.py
- sbi/inference/snre/__init__.py
- sbi/inference/snre/snre_b.py
- sbi/inference/snre/snre_base.py
- sbi/inference/snre/snre_c.py
- sbi/utils/sbiutils.py
- tests/inference_on_device_test.py
- tests/linearGaussian_snre_test.py
- tutorials/16_implemented_methods.ipynb
Dear SBI,
I would like to add our algorithm [NRE-C](https://arxiv.org/abs/2210.06170) to the SNRE section. I created the following checklist which I will update as the draft nears completion.
Let me know if there's anything else I can do!
Ben
> Contrastive Neural Ratio Estimation

- sbi/inference/base.py
- sbi/inference/snpe/snpe_base.py
- sbi/neural_nets/embedding_nets.py
- sbi/utils/sbiutils.py
- tests/embedding_net_test.py
- tests/inference_with_NaN_simulator_test.py
goal: have an embedding net for `NPE` that can handle varying number of iid trials, i.e., learn how the posterior changes as we change the number of trials. 
problem: our training procedure assume that `x` is a tensor with fixed dimensions, e.g., the trial dimension must be the same for all training data points. 
solution: given a training data set with a varying number of trials where the maximum number of trials is `max_num_trials`, pad all `x`s with smaller number of trials with `NaN`s such that `x.shape = (num_thetas, max_num_trials, dim_x)`. Adapt the `PermutationInvariantEmbeddingNet` such that it detects the `NaNs` and applies the `TrialEmbedding` only to the valid entries (using a loop over the batch). 
functional tests: seems to work fine for a Gaussian example
Questions: 
- any …
> add size invariant iid embedding nets, tests.

- sbi/inference/snre/snre_c.py
I noticed a bug in the code that implements contrastive neural ratio estimation. I fixed that here.
> Fixed a bug from CNRE

- tests/inference_on_device_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
to allow testing different density estimators, e.g., see #819
> add density estimators to tests.

- .pre-commit-config.yaml
- setup.cfg
- setup.py
not sure this will work directly locally. One has to re-install `sbi` to install `pre-commit` and then run `pre-commit install` locally to activate the hook. 
@michaeldeistler does this work fow you?
> pre-commit hook for isort and black.

- sbi/utils/sbiutils.py
I had some problems when calling the ``append_simulations` method. In a Jupyter Notebook, it would kill the kernel every time without further notice. In a script, one can see this is due to a segmentation fault. 
After some debugging, I spotted the problem when checking the Z-score of the data. In my case, the result of the simulation was two `vstacked` time series (external input and simulated time series; the tensor shape was `(batch_size, 2, n_data)`). For testing purposes, I was training the SBI only with a single realization of the external input, thus leading to 0 variance among all batches. 
Despite this not being a very common use case, the fact that it kills the Python kernel makes the problem difficult to track for the user: there is no error message and the debugger does not …
> Patched a potential segfault when appending simulations

- sbi/utils/conditional_density_utils.py
- sbi/utils/posterior_ensemble.py
- tests/ensemble_test.py
fixes #824 by passing on `allow_iid` from ensemble members. Adapts tests.
> fix: pass allow_iid, adapt tests.

- sbi/inference/posteriors/direct_posterior.py
- sbi/utils/torchutils.py
Previously, a call with `cuda:index` with `index != torch.cuda.current_device()` (default 0) would result in an assertion error. 
However, there are scenarios in which one wants to use a specific cuda index > 0. This is now possible.
> fix handling of multiple gpus.

- sbi/analysis/sbc.py
> fix: add x batch dim in sbc loop.

- CITATION.cff
- codemeta.json
This adds two popular citation metadata formats, based on the templates offered by the [Astrophysics Source Code Library](http://ascl.net/), see recent entry added for sbi at https://ascl.net/2306.002 (https://ascl.net/2306.002/CITATION.cff, https://ascl.net/2306.002/codemeta.json).
* https://citation-file-format.github.io/ (used e.g. by the Zotero plugin when bookmarking).
* https://codemeta.github.io/ (with a long list of _crosswalks_ that help other projects map metadata to their own packaging files, e.g. debian packages, wikidata, etc).
These citation files pertain to the software, but they encourage to cite the paper. There are best practices about citing the software directly that result in nuances in these files (e.g. use of 'preferred citation') that I have not investigated.
The …
> Add citation metadata in machine-parsable formats

- sbi/utils/torchutils.py
- tests/inference_on_device_test.py
potential fix for #853. 
a) We raise an error if the device passed via low/high does not match the device kward. E.g., if low/high have been moved to GPU already, but `device` is still on default "cpu". 
b) Alternatively, we could automatically use the device passed via low/high as the new device to be less verbose and to follow the user's obvious intention to have the prior on that device. 
For now, I implemented b). what do you think @michaeldeistler?
> bugfix: BoxUniform device handling.

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/docs/citation.md
- sbi/__version__.py
- sbi/inference/snpe/snpe_a.py
- setup.py
* update citation
* update contribution guidelines
* bump version
TODO:
> prepare release

- sbi/inference/base.py
- tests/linearGaussian_snpe_test.py
`simulate_for_sbi` calls `simulate_in_batches` with wrong positional arguments: 5afd40b added seed as an extra argument for `simulate_in_batches` which was not reflected at the call site. Thus, `show_progress_bar` (defaulting to True) is erroneously used as the value for seed. This PR proposes to fix the resulting spurious seeding by switching from positional to keyword arguments.
> Fix spurious seeding by switching to keyword args.

- tutorials/13_diagnostics_simulation_based_calibration.ipynb
The SBC results in the tutorial were not reproducible.
To fix this:
- multiple separate seeds for simulation, xo generation, and training.
- A few changes in wording to adjust for the new results
Also, I changed the way that the predictive are plotted. Previously, the limits were [0.75 *  x_o, 1.25 * x_o] but, because it was not reproducible, it could happen that x_o is very small and thus the limits are very close to each other. It is now [x_o - 1, x_o + 1].
Sorry for the huge diff, I tried in Jupyter lab and vs code but neither changed the indentation (which cases the diff)
> tutorial on SBC reproducibility

- sbi/analysis/tensorboard_output.py
@lappalainenj FYI. I tried with older versions of torch and with older versions of sbi and it always broke so assume that this bug happened a while ago (not sure if it happened with a version bump of torch or with sbi). Let me know if you know a more elegant fix!
> Fix error in tensorboard plotting

- tests/embedding_net_test.py
Test failing because of #888, but they run locally.
> change max_num_trials to make test pass

- tutorials/03_multiround_inference.ipynb
The inference object did not get instantiated in the multi round tutorial.
Closes #916
> Clarify tutorial on multi-round

- sbi/utils/torchutils.py
- tests/embedding_net_test.py
- tests/ensemble_test.py
- tests/inference_on_device_test.py
- tests/linearGaussian_mdn_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/mnle_test.py
- tests/multiprocessing_test.py
- tests/sbc_test.py
Problem: running `pytest -m "slow" tests/` currently takes for hours. 
This PR speeds up slow tests by
- removing duplicate test cases
- using fewer simulations or samples where possible
- using better mcmc params (-> `slice_np_vectorized` 🚀 )
TODO: 
Note: the speed up may seem suspicious, but I really did remove only a couple of tests where I was sure they are duplicates or not needed. Changing from default arg mcmc sampling to vectorized with better args just has a really big impact on speed (important note for #910)
> Profile slow and GPU tests

- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/importance_posterior.py
- sbi/inference/posteriors/mcmc_posterior.py
- sbi/inference/posteriors/rejection_posterior.py
- sbi/inference/posteriors/vi_posterior.py
- sbi/inference/potentials/base_potential.py
- sbi/inference/potentials/likelihood_based_potential.py
- sbi/inference/potentials/ratio_based_potential.py
- tests/potential_test.py
We now only require that the `potential_fn` takes `theta` and `x_o` as inputs.
```python
def potential(theta, x_o):
return sim.log_prob(theta, x_o) + prior.log_prob(theta)
posterior = MCMCPosterior(
potential_fn=potential,
proposal=posterior.set_default_x(x_o),
)
samples = posterior.sample((100,), x=x_o)
```
The newly added tests take `2.14 seconds` in total.
Closes #765
> Allow for the potential_fn to be a Callable

- sbi/utils/torchutils.py
- tests/inference_on_device_test.py
- tests/torchutils_test.py
We only support CUDA as GPU devices, but PyTorch 2.1 now supports Apple MPS chips as well (to some extend, see below). 
https://pytorch.org/docs/stable/notes/mps.html 
This PR changes the processing of passed device arguments to also allow MPS, e.g., instead of using `cuda` in the tests, we use `gpu` and parse the string to `mps:0` or `cuda:0` accordingly. 
- there is a problem when using MPS with `VIPosterior`, `q="nsf"` and `num_dims>1`. Sampling `q` then produces NaNs, see #948 
- PyTorch MPS backend is not implemented for a number of functions, e.g., `torch.linalg.cholesky`. So it uses CPU as a fallback there
- PyTorch MPS only supports float32 and `nflows` requires float64 (see here: https://github.com/bayesiains/nflows/blob/3b122e5bbc14ed196301969c12d1c2d94fdfba47/nflows/distribution …
> Allow Apple MPS as GPU device

- sbi/inference/posteriors/vi_posterior.py
- sbi/samplers/mcmc/slice.py
- sbi/samplers/vi/vi_divergence_optimizers.py
- sbi/samplers/vi/vi_pyro_flows.py
- sbi/samplers/vi/vi_utils.py
- sbi/types.py
- tests/vi_test.py
Will work for any default flow and VIPosterior input
> Pickle save for VIPosterior

- sbi/inference/base.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snre/snre_base.py
Fix for #921.
Moved `append_simulations` to `base.py`. There is some method specific arguments given to the `nle_nre_apt_msg_on_invalid_x` function, but purely for logging. 
So I added an algorithm argument in `base.py` and overwite it for the specific method in the `super()` call.
The `nle_nre_apt_msg_on_invalid_x` function makes `append_simulations` specific to SLNE, SNRE. So an alternative would be to have an intermediate object between `NeuralInference` and the estimators to make this clear?
> Fix 921 SNLE SNRE code duplication

- sbi/inference/snpe/snpe_base.py
- tests/inference_on_device_test.py
- tests/save_and_load_test.py
API change: For SNPE, one now has to use `direct` instead of `rejection` if one wants to directly sample from the density estimator. `direct` is also the new default.
Closes #918
> Introduce `sample_with="direct"` for SNPE

- CODE_OF_CONDUCT.md
Fixes contact details for the code of conduct. 
For the hackathon, we can link to this file and have everyone acknowledge it. 
Reviewers, please test the link to the form, it should work without google sign in.
> update code of conduct.

- sbi/neural_nets/density_estimators/__init__.py
- sbi/neural_nets/density_estimators/base.py
- sbi/neural_nets/density_estimators/flow.py
- tests/density_estimator_test.py
Density Estimators inherit nn.Module.
Also added sample_and_log_prob, with a naive implementation that can be easily overriden (following Zuko API).
Limitations:
- `net` must be a nn.Module (which is fine and consistent with the type hints).
> nn module as base class for density estimator

- sbi/utils/restriction_estimator.py
This is the PR for [#975](https://github.com/sbi-dev/sbi/issues/975). Both the restriction estimator and the restricted prior are now picklable. Both of them had separate issues relating to function definitions within functions that prevent pickle from serializing.
The refactoring I did to make them picklable were slightly bigger than initially expected. Please let me know if you disagree with any of the refactorings.
The main issue of the restriction estimator was in `build_classifier`, where a `build_nn` function was defined based on parameters. I found that the `build_classifier` function is not necessary, since all parameters come from the `RestrictionEstimator.__init__` anyway. I now just decide in the `__init__` what the instances `self._build_nn` should be.
The main problem of the …
> restriction estimator and restricted prior now picklable

- .github/workflows/tests.yml
- pyproject.toml
Clean up `pyproject.toml`:
- remove unsused deps, deps install multiple times.
- reorganize a bit (setuptools before external tools config).
Part of #1008
> CLN pyproject.toml

- pyproject.toml
Problem: when setting things up with python 3.9 or higher, it will install `pre-commit` v3.6.0 or higher, which causes a lot of formatting changes. We don't want those for now (the hackathon). 
Solution: pin pre-commit to 3.5.0. This will work with higher Python versions as well, (but not the other way around).
> pin pre-commit to 3.5.0

- sbi/inference/snpe/snpe_a.py
Adds a `**kwargs` to `SNPE_A.build_posterior(...)` and then does 
```python
self._posterior = super.build_posterior(
posterior_estimator=wrapped_density_estimator,  # type: ignore
prior=prior,
**kwargs,
)
```
instead of building the posterior directly with `DirectPosterior(...)`. 
Fixes #988
your code.
> Add kwargs to SNPE_A.build_posterior to match base class API

- sbi/neural_nets/flow.py
- sbi/neural_nets/mdn.py
As raised in #807, if you create an embedding net that contains a `BatchNorm[N]d` layer, the forward passes used to determine embedding net output size fail because the BatchNorm layer checks for batches with more than one datapoint. Manuel suggests either providing more than one datapoint to the forward pass or setting the embedding net to eval mode. Eval mode seems preferable as it also doesn't affect the running statistics potentially tracked by the module, so `embedding_net.eval()` was added where needed. Density estimators are explicitly set to training mode in respective inference methods so this change should not affect anything downstream.
Fixes #807
None
None
the PR. If you're unsure about any of them, …
> Set embedding nets to eval before single forward pass for batchnorm bug

- .github/workflows/tests.yml
With this change, Github Action will look for a cached dependency installation based on the same `pyproject.toml`, load it from its cache and not need to install it again. This should make all CI tests run faster.
> Cache dependencies in Github Action (#1027)

- sbi/examples/minimal.py
- sbi/inference/__init__.py
- sbi/inference/base.py
- sbi/utils/user_input_checks.py
- tests/ensemble_test.py
- tests/inference_on_device_test.py
- tests/inference_with_NaN_simulator_test.py
- tests/linearGaussian_mdn_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/mcmc_test.py
- tests/plot_test.py
- tests/posterior_nn_test.py
- tests/posterior_sampler_test.py
- tests/simulator_utils_test.py
- tests/user_input_checks_test.py
Deprecates `prepare_for_sbi` and replaces it with `process_prior` and `process_simulator` in the rest of the codebase (already replaced in tutorial notebooks).
Fixes #1082
> Deprecate `prepare_for_sbi`

- sbi/neural_nets/flow.py
- sbi/utils/sbiutils.py
- sbi/utils/zukoutils.py
Currently, the z-scoring layer for zuko transforms uses the `Unconditional` class from zuko, however this throws a pyright error when creating zuko flows, as `Unconditional` does not inherit from `LazyTransform`, which is expected to be the class of all transforms in a zuko `Flow` object. Here we create a temporary workaround, and will also start an issue in zuko for this.
Fixes #1074 
> Unconditional LazyTransform workaround

- sbi/samplers/mcmc/slice_numpy.py
Pyright raised errors in newer Python versions (e.g. 3.10) which it didn't do in our CI pipeline running on 3.8. First step towards #1102
> Fix issues pyright raises on newer Python versions

- tests/conftest.py
- tests/ensemble_test.py
- tests/inference_on_device_test.py
- tests/inference_with_NaN_simulator_test.py
- tests/linearGaussian_mdn_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/mcmc_test.py
- tests/plot_test.py
- tests/posterior_nn_test.py
- tests/posterior_sampler_test.py
- tests/simulator_utils_test.py
- remove helper functions from tests when they are not needed
- add pytest hook to skip GPU tests when no devices are available: running `pytest tests/` locally without GPU will skip all `gpu` marked tests, i.e., act like `pytest -m "not gpu" tests/`
Fixes #1093 #1098
> Remove helpers from tests, skip GPU tests.

- .pre-commit-config.yaml
- ruff linting was not working during CI because of wrong `kwarg` `diff` (my bad). 
- too long line were pushed into `main` as a consequence. 
both fixed with this commit.
> ruff linting hook, fix line lengths.

- sbi/neural_nets/density_estimators/nflows_flow.py
- sbi/neural_nets/density_estimators/zuko_flow.py
Adds a `inverse_transform` method to the `NFlowsFlow` and `ZukoFlow` objects.
Fixes #1085 
...
...
your code.
- [x ] I have read and understood the [contribution
- [x ] I agree with re-licensing my contribution from AGPLv3 to Apache-2.0.
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I performed linting and formatting as described in the [contribution
> inverse_tranform methods for nflows and zuko

- tests/multiprocessing_test.py
Restrict to number of cores that your machine actually has to fix.
fixes #1111
> multiprocessing only with num_cores

- sbi/inference/posteriors/importance_posterior.py
- sbi/samplers/importance/importance_sampling.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snre_test.py
fixes #933 
- no pbar for `importance_sample` because it happens instantly.
- includes an unrelated change to the SNLE tests (the unnecessary if-else case).
> Fix 933: add progress bars to Importance Posterior

- .github/PULL_REQUEST_TEMPLATE.md
- sbi/neural_nets/flow.py
The slow test `tests/linearGaussian_snle_test.py::test_c2st_and_map_snl_on_linearGaussian_different` is failing because we are passing `nflows` related kwargs to the `zuko` flow builder. 
Excluding those kwargs fixes the problem.
> Fix zuko kwargs

- sbi/samplers/mcmc/pymc_wrapper.py
Two errors in `PyMCSampler` fixed here:
* check for whether gradient tracking needed in line 141 of `sbi.samplers.mcmc.pymc_wrapper` looked for matching step class instead of the string value actually used and expected
* `pymc.Model()` incorrectly set up using a prior distribution and additional likelihood term which does not result in the desired distribution. Now using `pymc.DensityDist` which directly defines the distribution using given potential function
With these changes `test_c2st_pymc_sampler_on_Gaussian` passes locally for all sampling methods.
Fixes #1127 
help! This is simply a reminder of what we are going to look for …
> fix errors in pymc sampler implementaton

- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/potentials/likelihood_based_potential.py
- sbi/inference/potentials/posterior_based_potential.py
- sbi/inference/potentials/ratio_based_potential.py
- sbi/inference/snle/mnle.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/neural_nets/categorial.py
- sbi/neural_nets/density_estimators/categorical_net.py
- sbi/neural_nets/density_estimators/mixed_density_estimator.py
- sbi/neural_nets/density_estimators/nflows_flow.py
- sbi/neural_nets/density_estimators/shape_handling.py
- sbi/neural_nets/density_estimators/zuko_flow.py
- sbi/neural_nets/mnle.py
- sbi/utils/user_input_checks.py
- tests/base_test.py
- tests/density_estimator_test.py
All density estimators now have a unified format of their input and output shapes. 
- `input` must have shape `(sample_dim: int, batch_dim: int, *event_shape: Tuple[int])`
- `condition` must have shape `(batch_dim: int, *event_shape: Tuple[int])`
- `batch_dim` of `input` and `condition` must be the same for `log_prob`.
**`density_estimator.log_prob(input, condition)`**
```
input: (sample_input, batch_input, *event_shape_input)
condition: (batch_condition, *event_shape_condition)
returns: (sample_input, batch_input)
raises: batch_input != batch_condition
```
**`density_estimator.sample(sample_shape, condition)`**
```
sample_shape: (*sample_shape)
condition: (batch_condition, *event_shape_condition)
returns: (*sample_shape, batch_condition, *event_shape_input)
``` …
> Shape conventions for all DensityEstimators

- sbi/inference/abc/mcabc.py
- sbi/inference/abc/smcabc.py
- sbi/inference/posteriors/base_posterior.py
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/ensemble_posterior.py
- sbi/inference/posteriors/importance_posterior.py
- sbi/inference/posteriors/mcmc_posterior.py
- sbi/inference/posteriors/rejection_posterior.py
- sbi/inference/posteriors/vi_posterior.py
- sbi/inference/snle/mnle.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snpe/snpe_c.py
- sbi/inference/snre/snre_base.py
- sbi/neural_nets/categorial.py
- sbi/neural_nets/density_estimators/base.py
- sbi/neural_nets/density_estimators/categorical_net.py
- sbi/neural_nets/density_estimators/mixed_density_estimator.py
- sbi/neural_nets/density_estimators/nflows_flow.py
- sbi/neural_nets/density_estimators/zuko_flow.py
- sbi/neural_nets/flow.py
- sbi/neural_nets/mdn.py
- sbi/neural_nets/mnle.py
- sbi/utils/user_input_checks.py
- tests/user_input_checks_test.py
Closes #1135 
Does the following things:
- introduce `input_shape` to the `DensityEstimator`
- the `inference` classes uses the `input_shape` and `condition_shape` of the `DensityEstimator` to infer `._x_shape`. `inference._x_shape` no longer contains a batch dimension.
- the posterior no longer performs checks for `x_shape`. These checks should be fully handled by the `DensityEstimator`.
your code.
guidelines](https://github.com/sbi-dev/sbi/blob/main/CONTRIBUT …
> Give all DensityEstimators an input_shape

- sbi/inference/posteriors/ensemble_posterior.py
See @janfb's comment in #1138 
> we don't need the allow_iid check anymore?
> Fixup for process_x in EnsemblePosterior

- sbi/inference/snle/mnle.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/neural_nets/density_estimators/base.py
- sbi/neural_nets/density_estimators/categorical_net.py
- sbi/neural_nets/density_estimators/mixed_density_estimator.py
- sbi/neural_nets/density_estimators/nflows_flow.py
- sbi/neural_nets/density_estimators/zuko_flow.py
- tests/density_estimator_test.py
In #1066, we had defined that `log_prob` and `loss` have the same input and output shapes:
```
density_estimator.log_prob(input, condition)
```
```
input: (sample_input, batch_input, *event_shape_input)
condition: (batch_condition, *event_shape_condition)
returns: (sample_input, batch_input)
raises: batch_input != batch_condition
```
However, for `.loss`, we are now removing the `sample_dim`. Therefore, the `.loss` function now has the following signature:
```
input: (batch_input, *event_shape_input)
condition: (batch_condition, *event_shape_condition)
returns: (batch_input)
raises: batch_input != batch_condition
```
help! This is …
> DensityEstimator.loss does not take `sample_dim`

- sbi/neural_nets/density_estimators/nflows_flow.py
- tests/density_estimator_test.py
> Fixes current density estimator bug

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- Separate workflow for the linting.
- Move pyright in dedicated process to avoid failing the test on type checks.
> MTN better split the linting process from the CI/CD workflow

- sbi/utils/torchutils.py
- sbi/utils/user_input_checks.py
- tests/analysis_test.py
- tests/conftest.py
Refactors warnings related to GPU usage. Fixes a warning about `torch.set_default_tensor_type()` being deprecated as of PyTorch 2.1. 
Fixes #1168 
Does is also fix #1167?
> Refactor gpu warnings

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/potentials/likelihood_based_potential.py
- sbi/inference/potentials/posterior_based_potential.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_a.py
- sbi/inference/snpe/snpe_base.py
- sbi/neural_nets/__init__.py
- sbi/neural_nets/density_estimators/__init__.py
- sbi/neural_nets/density_estimators/base.py
- sbi/neural_nets/density_estimators/categorical_net.py
- sbi/neural_nets/density_estimators/mixed_density_estimator.py
- sbi/neural_nets/density_estimators/nflows_flow.py
- sbi/neural_nets/density_estimators/zuko_flow.py
Implements an abstract base class for estimators, which has:
- `input_shape` 
- `condition_shape`
- abstract loss function.
Will close #966.
Will replace #1072 .
- Density estimator `sample` and `log_prob` could be abstract methods, instead of raising a NotImplementedError
> feat: base conditional estimator class

- sbi/samplers/mcmc/slice_numpy.py
fixes inf values being returned by the slice_numpy mcmc sampler
Fixes #1060. Also related to #910
The issue was not in the sampler "diverging", c.f. #910:
> The main reason seems to be the number of warmup steps. If it is too small, chains have not converged and samples diverge (why?)
Instead, we generated the samples to return initially with `np.empty()`, but did not account for the tuning of the bracket width, so we never defined the first entries of the sampels returned. This is why increasing warm up steps also fixed the issue - the nan values were completely removed if the warm_up steps were increased enough.
> slice_numpy_mcmc tuning fix

- pyproject.toml
- tests/conftest.py
- tests/density_estimator_test.py
- tests/linearGaussian_snpe_test.py
- tests/save_and_load_test.py
I changed the `pytest` settings to `xfail=strict`. This means that when a test that is supposed to fail passes, this will results in a failure (was ignored before). This has the advantage that notice when a bug or missing feature was fixed "by accident" (see SNRE example below). 
- fix conditional sampling test
- set fast mcmc args warmup steps=1
- fix `xpassing` SNRE pickling test which was already fixed some time ago.
> test: refactor tests, make xfail strict.

- pyproject.toml
- sbi/neural_nets/flow.py
- sbi/utils/sbiutils.py
- sbi/utils/zukoutils.py
adapt to recent `zuko` release: 
- `UnconditionalTransform` now available
- `BernsteinPoynomialFlow` has different args: `linear` deprecated`, `bound` is not passed on.
> fix: zuko UnconditionalTransform, fix BPF args.

- sbi/inference/posteriors/importance_posterior.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- tests/posterior_nn_test.py
Adds the possibility of importance sampling.
Fixes #919
> importance sampling posterior

- sbi/diagnostics/tarp.py
- sbi/utils/metrics.py
- tests/tarp_test.py
Tarp is a diagnotics method, which can help identify over-/underdispersion and bias in trained neural posteriors. The corresponding paper is located here:
https://arxiv.org/abs/2302.03026
the repo code for numpy is here:
https://github.com/Ciela-Institute/tarp/
No, this was part of the Mar 2024 SBI hackathon in Tübingen
Not yet, I am trying to reproduce the examples given in the paper. At a later point in time, I'd like to bring the tests as well as a tutorial in line to what is available with sbc.
your code. …
> feat: calibration with tarp

- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/neural_nets/classifier.py
- sbi/neural_nets/factory.py
- sbi/neural_nets/flow.py
- sbi/neural_nets/mdn.py
- sbi/utils/__init__.py
- sbi/utils/nn_utils.py
- sbi/utils/user_input_checks.py
- tests/inference_on_device_test.py
The starting point for this PR is  #1161, the incorrect warning that embedding net and data device do not match.
On the way I realized that we are treating the `embedding_net` as separate net that can have its own device, different from the actual net. I think this does not make sense. 
In general, the device handling should be centralized, e.g., have a single entry point. At the moment, this entry point is the inference object, e.g., `SNPE(..., device=device)`. But are the different scenarios: 
1. user passes a model str to `SNPE`: all good, device handling is centralized via the `device`
2. user passes a custom net, which could be on a device already. Then this device must match the `device` passed to `SNPE`.
3. user uses e.g., `posterior_nn` to build a flow with an embedding net. …
> fix: remove emb net device handling, refactor get_numel

- docs/mkdocs.yml
- tutorials/05_embedding_net.ipynb
- tutorials/13_diagnostics_simulation_based_calibration.ipynb
- tutorials/14_iid_data_and_permutation_invariant_embeddings.ipynb
Our tutorials should be at the state of the released sbi version, not at the state of the github version. This PR fixes this. After being approved and merged I will redeploy.
> reset tutorials to released sbi version

- tests/metrics_test.py
Simplified the tests for posterior shrinkage and posterior zscore by using pytest marks to make the code cleaner and easier to manage.
Fixes #1118 
your code.
> Refactor: Simplify posterior shrinkage tests with pytest marks

- sbi/inference/base.py
- tests/inference_on_device_test.py
- tests/linearGaussian_mdn_test.py
- tests/linearGaussian_snle_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/mcmc_test.py
- tests/plot_test.py
- tests/posterior_nn_test.py
- tests/posterior_sampler_test.py
`simulate_for_sbi` is causing `main` to fail because it now requires the passed simulator to be able to handle `numpy` arrays. This works only if the simulator has been processed using `process_simulator` before. 
Along the way, I also removed all `simulate_for_sbi` calls from the tests because I believe that we don't need them there. Most priors and simulators we use during testing are torch distributions and simple linear Gaussian simulators. They can be sampled directly, i.e., just sampling the prior and passing the entire `theta` to the simulator. There is no need to use`process_simulator` or `simulate_for_sbi`. 
Of course, there are a couple of exceptions, e.g., when composing independent priors we need to process them.
> refactor: remove simulate_for_sbi from tests.

- pyproject.toml
- sbi/analysis/plot.py
- sbi/analysis/sensitivity_analysis.py
- sbi/diagnostics/lc2st.py
- sbi/diagnostics/tarp.py
- sbi/inference/snle/snle_base.py
- sbi/inference/snpe/snpe_base.py
- sbi/inference/snre/snre_base.py
- sbi/samplers/vi/vi_divergence_optimizers.py
- sbi/utils/metrics.py
- sbi/utils/restriction_estimator.py
- sbi/utils/sbiutils.py
- tests/metrics_test.py
> fix #1204: c2st with constant features; fix pyright.

- tests/lc2st_test.py
- tests/linearGaussian_snpe_test.py
- tests/linearGaussian_snre_test.py
- tests/mnle_test.py
- tests/multiprocessing_test.py
- tests/sbc_test.py
slow tests for tsnpe sir need a bit more samples. Probably because the random state changed because of removing `simulate_for_sbi`. 
- added a couple of other small changes to make slow tests pass again.
> fix: slow tests.

- sbi/inference/posteriors/mcmc_posterior.py
- tests/posterior_nn_test.py
when the `num_chains` was higher or not a multiple of the number of samples to be generated with MCMC `sample_batched`, the samples were reshaped incorrectly: The remaining samples were pushed into the last dimension here: 
https://github.com/sbi-dev/sbi/blob/b27544891ab1418ff9214886d580d2bf0ba43a3b/sbi/inference/posteriors/mcmc_posterior.py#L467
This is a fix where we first collect all the generated samples from the chains (possibly more than needed), then select as many as we need and then reshape into the desired `(*sample_shape, batch_size, input_shape)`. 
I also added tests that cover all the cases, which makes them quite slow.
> fix: batched mcmc reshaping

- sbi/diagnostics/sbc.py
- sbi/inference/posteriors/mcmc_posterior.py
- sbi/inference/posteriors/rejection_posterior.py
- sbi/neural_nets/mnle.py
- sbi/samplers/mcmc/slice_numpy.py
- sbi/utils/sbiutils.py
- sbi/utils/user_input_checks.py
- sbi/utils/user_input_checks_utils.py
- tests/mnle_test.py
- more fixes for slow tests. They are passing locally on `python3.8` but somehow fail on GitHub actions. 
- some formatting changes in `MCMC` related warnings.
> Fix slow tests and warnings

- sbi/analysis/plot.py
This fixes #1219. The issue was that on every call to `plt_1d_hist` or `plt_2d_hist`, the `bins` kwarg was directly saved over, which changed the behavior of the next call. Instead I just save temporary copies of the kwargs on these calls.
Also add default aspect to "auto" for the offdiag plots.
> Fix pairplot histogram bins and aspect ratio

- sbi/analysis/conditional_density.py
- sbi/inference/potentials/posterior_based_potential.py
- sbi/utils/conditional_density_utils.py
Fix type annotation in class 'ConditionedPotential'. Correct return type
of the function 'posterior_estimator_based_potential'
- The argument `potential_fn` of the class `ConditionedPotential` must be of type `BasePotential`
Fixes #1055
...
...
your code.
with `pytest.mark.slow`.~
> Fix type annotation in class 'ConditionedPotential'.

- sbi/utils/nn_utils.py
- sbi/utils/user_input_checks.py
Fix for erroneous warnings saying tensors are on different devices when they are on the same device. 
This bug occurs when PyTorch `device` objects are used rather than their string representations. In the comparisons that check the tensors are on the right device one side is cast to a string but not the other. When `device` objects are used this leads to comparing an object to a string and hence them not being equal and a warning being raised, e.g.,
```text
UserWarning: Data x has device 'cuda:0'. Moving x to the data_device 'cuda:0'. Training will proceed on device 'cuda:0'.
theta, x = validate_theta_and_x(
```
This bug is fixed by casting both sides of the comparison to strings. 
None
Minimum working example to illustrate bug and replicate the warning shown above,
```python
"""MWE …
```
> Fix erroneous warnings about different devices

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/lint.yml
- pyproject.toml
- sbi/analysis/plot.py
- tests/sbc_test.py
- tests/tutorials_test.py
- fix tests
- update deps
fixes #1229 
fixes #1189 
fixes #1150
> Drop python3.8 and torch1.12; update dependencies

- README.md
- docs/docs/faq/question_01_leakage.md
- docs/docs/faq/question_02_nans.md
- docs/docs/faq/question_03_pickling_error.md
- docs/docs/faq/question_06_resume_training.md
- docs/docs/index.md
- docs/docs/tutorials/index.md
- sbi/inference/trainers/base.py
- tutorials/00_getting_started.ipynb
- tutorials/01_gaussian_amortized.ipynb
- tutorials/04_embedding_networks.ipynb
- tutorials/05_conditional_distributions.ipynb
- tutorials/18_training_interface.ipynb
- tutorials/Example_01_DecisionMakingModel.ipynb
- refactor first paragraphs
- add new methods
- add aAI to credits. 
- fix all links in code, tutorials and FAQ because we changed "tutorial <- tutorials"
fixes #1214
> docs: refactor readme.

- MANIFEST.in
- pyproject.toml
adds `__init__.py` to `score` to include it into the package.
> fix: init file for score module, remove examples

- tests/mcmc_test.py
CD tests are failing on `main` right now `C2ST: 0.6028045112781955 <= (0.5 + 0.1)` for `test_c2st_pymc_sampler_on_Gaussian`. I cannot reproduce this failure locally (neither on python 3.9 nor on 3.12). However, to get github actions to run, I slightly increased the number of samples.
> fixup for failing hmc test

- docs/docs/faq/question_05_pickling.md
See #1254
Sampling of old posteriors under v0.23.1 leads to errors. I don't think that these errors have an easy fix, so I am adding this to the FAQ.
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], line 1
----> 1 posterior.sample((100,), x=torch.ones((1, 3)))
File [~/anaconda3/envs/sbidebug/lib/python3.12/site-packages/sbi/inference/posteriors/direct_posterior.py:111](http://localhost:8888/lab/workspaces/~/anaconda3/envs/sbidebug/lib/python3.12/site-packages/sbi/inference/posteriors/direct_posterior.py#line=110), in DirectPosterior.sample(self, sample_shape, x, max_sampling_batch_size, sample_with, show_progress_bars)
108 num_samples = …
```
> update pickling FAQ

- sbi/inference/__init__.py
- sbi/inference/trainers/base.py
- sbi/utils/simulation_utils.py
- tests/inference_with_NaN_simulator_test.py
- tests/user_input_checks_test.py
Move simulate_for_sbi to utils
Fixes #1240 
your code.
> Refactor `simulate_for_sbi` location

- sbi/utils/restriction_estimator.py
- tests/inference_with_NaN_simulator_test.py
Make `RestrictedPrior` a proper `torch.Distribution` with the required methods. The support is taken from the underlying base prior, or raised as not implemented. 
This is fix the problem when using `process_prior` -- it will not be wrapped as a `CustomPrior` and it will also work with transforms, e.g., for MCMC-based posteriors. 
Fixes #790
> fix: make RestrictedPrior a distribution; extend test

- CONTRIBUTING.md
- tutorials/18_training_interface.ipynb
I was happy to see the recent exposure of more control for the [training loop](https://sbi-dev.github.io/sbi/latest/tutorials/18_training_interface/#training-the-density-estimator). As discussed with @janfb, I added a small example on how rewrite the training loop to exploit such a `DataLoader`.
I didn't create an issue for this.
I basically added a section which documents this:
``` python
optw = AdamW(list(maf_estimator.parameters()), lr=5e-4)
nepochs = 50
for ep in range(nepochs):
for idx, (theta_batch, x_batch) in enumerate(train_loader):
optw.zero_grad()
losses = maf_estimator.loss(theta_batch, condition=x_batch)
loss = torch.mean(losses)
loss.backward()
optw.step()
if ep % 10 == 0:
print("last loss", loss.item())
```
Can you please let me know, how to clean a notebook before I commit …
> Adding example for custom DataLoader to tutorial 18

- sbi/inference/posteriors/direct_posterior.py
- sbi/utils/sbiutils.py
- sbi/utils/user_input_checks.py
- tests/posterior_nn_test.py
fixes #1256 
Note: I removed `warn_on_batched_x` because it was shown whenever a batched `x` is passed, i.e., even when explicitly calling `sample_batched`. I think we do not need to issue the warning when calling the batched methods because users explicitly call those methods for the batched case.
For the iid case, in NPE, the user has to use a corresponding embedding net anyways, so this warning is also not helpful. 
For the iid base in likelihood-based methods, it is natural that we can sample iid data, so also no need to issue the warning.
> Fix npe iid handling

- sbi/utils/restriction_estimator.py
My bad, this bug was introduced in #1257 and not detected because it was hidden in the slow tests.
> fix bug introduced in #1257

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/build_docs.yml
- .github/workflows/publish.yml
- pyproject.toml
- tests/strip_notebook_outputs.py
- https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
- https://docs.pypi.org/trusted-publishers/adding-a-publisher/
> build: automatic nb stripping and pypi upload

- sbi/analysis/plot.py
- tests/plot_test.py
- fixes #1260 by including the points, if passed, into the automatic inferring of the plotting limits. 
- some refactoring.
> fix #1260: include points in plotting limits

- README.md
- docs/docs/index.md
At the moment, the docs website landing page starts a bit abruptly directly with the code snippet. 
I think it is nice to have the same short intro text that we use in the updated readme as well. 
What do you think?
In the future it would be nice to show a plot there as well.
> docs: add readme intro to docs landing page

- sbi/inference/posteriors/ensemble_posterior.py
- sbi/inference/trainers/fmpe/fmpe.py
- sbi/inference/trainers/npse/npse.py
- sbi/inference/trainers/nre/nre_base.py
- tests/test_utils.py
`x_shape` as argument to posteriors is deprecated. We still have for backwards compatibility in some posteriors. 
However, we don't need it in the new posteriors. We can also remove it in some internal uses - which is done in this PR.
> refactor: remove deprecated x_shape where not needed.

- CHANGELOG.md
- sbi/__version__.py
- add 23.1 content to changelog
- draft content for 23.2
> build: bump version, draft change log.

- sbi/inference/potentials/posterior_based_potential.py
- tests/linearGaussian_fmpe_test.py
- tests/linearGaussian_snpe_test.py
Somehow the iid handling for NPE was failing because is was not checking for the shape > 1, but directly failing when `x_is_iid=True`.
> fix: posterior potential iid handling

- sbi/inference/potentials/likelihood_based_potential.py
- sbi/inference/potentials/posterior_based_potential.py
- sbi/inference/potentials/ratio_based_potential.py
- sbi/inference/potentials/score_based_potential.py
- tests/linearGaussian_fmpe_test.py
- tests/linearGaussian_snpe_test.py
- tutorials/05_conditional_distributions.ipynb
- set default `None` in all potentials
- fix tutorial 05
> Fix iid error handling

- sbi/utils/user_input_checks.py
- sbi/utils/user_input_checks_utils.py
- tests/user_input_checks_test.py
Closes #1285 an #1284
1D pytorch distributions such as `torch.distributions.Exponential`, `.Uniform`, or `.Normal` do not, by default return __any__ sample or batch dimension. E.g.:
```python
dist = torch.distributions.Exponential(torch.tensor(3.0))
dist.sample((10,)).shape  # (10,)
```
`sbi` will raise an error that the sample dimension is missing. A simple solution is to add a batch dimension to `dist` as follows:
```python
dist = torch.distributions.Exponential(torch.tensor([3.0]))
dist.sample((10,)).shape  # (10, 1)
```
Unfortunately, this `dist` will return the batch dimension also for `.log_prob():
```python
dist = torch.distributions.Exponential(torch.tensor([3.0]))
samples = dist.sample((10,))
dist.log_prob(samples).shape  # (10, 1)
```
This will lead to unexpected errors in …
> Wrap 1D PyTorch distributions

- sbi/neural_nets/embedding_nets/cnn.py
When configuring the CNN-based embedding layer using `sbi.neural_nets.embedding_nets.CNNEmbedding`, setting the parameters for `num_cnn_layers`, `kernel_size`, and `pool_kernel_size` incorrectly may result in a vague error message, such as:
`RuntimeError: Given input size: (6x4x4). Calculated output size: (6x0x0). Output size is too small.`
**Proposed Solution**: 
Since the `cnn_output_size` is recalculated after each layer, a CNN setup with excessive depth results in an output size of zero. This could be leveraged to alert the user about appropriate layer size configurations or to adjust other parameters accordingly.
> Check if 'cnn_output_size' is zero in CNNembedding. 

- CHANGELOG.md
- tests/lc2st_test.py
- tests/linearGaussian_fmpe_test.py
- tests/linearGaussian_snpe_test.py
Fix broken tests to prepare for release.
#1276 caused issues in conditional sampling tests
#1279 caused issues with LC2ST accuracy tests
> fixup for failing conditional sampling tests

- sbi/analysis/plot.py
Typo in y-axis label.
No.
No.
No.
your code.
with `pytest.mark.slow`.~
guidelines](https://github.com/sbi-dev/sbi/blob/main/CONTRIBUTING.md)~
For the reviewer:
> Correted typo in y-axis label

- docs/docs/faq/question_04_gpu.md
Commit 109d7e9cda98cf9c75579592be7f974ad925c3d9 renamed the embedding networks notebook. This PR adjusts sources to changes.
Fixes # (issue)
...
...
your code.
For the reviewer:
> docs: update embedding networks notebook

- sbi/inference/posteriors/mcmc_posterior.py
- tests/save_and_load_test.py
This PR address the issue of the MCMCPosterior not being pickable after running sample.
Fixes #1278  
Extended the save and load tests to be performed after calling sample and log_prob once.
> Fix pickle issues in MCMC posterior + test

- sbi/inference/posteriors/ensemble_posterior.py
In sbi.inference.posteriors, the [EnsemblePosterior](https://github.com/sbi-dev/sbi/blob/main/sbi/inference/posteriors/ensemble_posterior.py) instantiation would return a **TypeError** when passing weights (torch.Tensor or List[float]).  The condition  `elif weights is Tensor or weights is List` would always return False, I changed the condition to` elif isinstance(weights, Tensor) or isinstance(weights, List)`, where Tensor is the torch class of the same name.
No, to the best of my knowledge.
The only "fix" is intended to properly test the type of the weights attribute of [EnsemblePosterior](https://github.com/sbi-dev/sbi/blob/main/sbi/inference/posteriors/ensemble_posterior.py) in case it is not None.
I do not know whether I should have opened an new issue instead of doing a minor …
> Minor fix for EnsemblePosterior weights.setter

- tests/ensemble_test.py
Adds a test case for weight validation in EnsemblePosterior to verify proper handling of different weight formats (list, tensor) and error cases. The test ensures the API correctly validates weights without running full posterior accuracy checks.
Fixes #1304
your code.
For the reviewer:
> [test] add tests for ensemble posterior weights

- sbi/diagnostics/sbc.py
- sbi/diagnostics/tarp.py
- sbi/utils/diagnostics_utils.py
fixes #1320 
- exposes `use_batched_sampling` in `run_tarp`
- catch `AssertianError` raised in MCMCPosterior when using batched sampling with something else than `slice_np_vectorized`
- add warning when sampling for a batch of `x` without batched sampling.
> expose batched sampling option; error handling

- README.md
- docs/docs/index.md
- docs/docs/install.md
* Add install instructions from conda-forge for pixi and conda to README.
- c.f. https://github.com/conda-forge/sbi-feedstock
* Add conda-forge badge. [![Conda Version](https://img.shields.io/conda/vn/conda-forge/sbi.svg)](https://github.com/conda-forge/sbi-feedstock)
* Add install instructions from conda-forge for pixi and conda to docs.
- Correct minimum required Python to Python 3.9.
- Update example python version in conda env creation to Python 3.12.
Related to https://github.com/sbi-dev/sbi/issues/1322
N/A
With [`pixi`](https://pixi.sh/) you can now get a fully working CUDA environment very fast (under 30 seconds) with the following
```console
$ mkdir example && cd example
$ pixi init
```
Add in 
```toml
[system-requirements]
cuda = "11"
```
to `pixi.toml`
(here I'm using CUDA …
> docs: Add conda-forge install instructions

- sbi/neural_nets/estimators/base.py
- sbi/neural_nets/estimators/nflows_flow.py
- sbi/neural_nets/estimators/zuko_flow.py
In our current shape convention, `condition` does not have a `sample_dim`, but the docstring was saying something else. 
fixes #1316
> Fix #1316: remove sample_dim docstring for condition.

- tutorials/03_density_estimators.ipynb
- tutorials/08_crafting_summary_statistics.ipynb
- tutorials/12_iid_data_and_permutation_invariant_embeddings.ipynb
- tutorials/15_importance_sampled_posteriors.ipynb
new version of @zinaStef's tutorial typo fixes. Replaces #1298
> docs: fix tutorial typos

- sbi/utils/sbiutils.py
- tests/inference_on_device_test.py
- add test for multi-round training with mdn on GPU
- fix device bug for `constant`
- fix gpu-mcmc tests
fixes #1343
> fix #1343 device handling in mog_log_prob

- tests/tutorials_test.py
During the release, the GitHub action that executes and then strips all notebooks before building the docs failed because the decision making example notebook took longer than 10min to execute. Here, we increase to timeout to avoid this failure in the future.
> increase tutorial test timeout

- sbi/neural_nets/net_builders/mnle.py
- tests/mnle_test.py
- tests/tutorials_test.py
- tutorials/16_implemented_methods.ipynb
- tutorials/Example_01_DecisionMakingModel.ipynb
The change to detecting NaNs in all losses already payed off: In MNLE, we were using the `log_transform=True` per default. This was performing better and makes sense for positive data like reaction times in decision-making experiments. However, it does not make sense in general. In implemented methods tutorial we were passing Gaussian data, which then caused NaNs after the log-transform, causing the loss to become NaN. 
This PR
- changes the default to `False` and add small improvements to the tutorial notebook. 
- adapt all tutorial and example notebooks to explicitly apply the log transform when dealing with bounded decision-making data
- fix bug in Decision-Making Example notebook that caused the time-our error in Continuous-Deployment (`main` tests failing)
@manuelgloeckler / …
> Fix failing tutorials, change MNLE default for log_transform to False

- sbi/inference/potentials/likelihood_based_potential.py
- sbi/utils/sbiutils.py
- tests/inference_on_device_test.py
- tests/mnle_test.py
There were a couple of bugs when using the `MCMCPosterior` with a `conditioned_potential`, which are fixed in this PR. 
fixes #1364
> Fix conditional posterior shape and device bugs.

- sbi/samplers/vi/vi_divergence_optimizers.py
- tests/mcmc_test.py
- tests/posterior_sampler_test.py
a new pyright version was detecting that `HYPER_PARAMETERS` might be uninitialized in the subclasses so that `+=` would not work.
This PR fixes it by initializing it with an empty list in that case.
> fix: type fix in VI subclasses. xfail pymc tests.

- sbi/inference/posteriors/mcmc_posterior.py
The warning on the number of chains for batched sampling for a MCMC Posterior hat `larger number` twice in the string. 
Also, despite reducing the number of chains, reducing the batch size might be a suitable solution as well. 
No.
No.
No.
your code.
with `pytest.mark.slow`.~
For the reviewer:
> duplication of 'large number' in warning

- sbi/inference/posteriors/direct_posterior.py
- sbi/inference/posteriors/score_posterior.py
- sbi/inference/potentials/score_based_potential.py
- sbi/inference/trainers/npse/npse.py
- sbi/samplers/rejection/rejection.py
- sbi/samplers/score/diffuser.py
- sbi/utils/restriction_estimator.py
- tests/linearGaussian_npse_test.py
- tests/posterior_nn_test.py
This introduces some additional features for score estimation named in #1226, namely:
#1226
- Currently, calling `score_based_posterior.map()` is still quite slow. We get the gradient of the log probs with respect to `theta` by using the score estimator, but still computing the log-probs explicitly in `gradient_ascent`, which is more expensive. To get around this, we save a low-accuracy ode_flow to calculate the log-probs more quickly. Ideally, we might want to write a custom `gradient_ascent` function for calculating the MAP for score estimators to avoid doing this altogether.
- I increased the tolerance of the test in `linearGaussian_npse_test.py::test_npse_map` - as far as I can tell, the reason this failed with the lower tolerance is not because of MAP calculation, but because …
> additional features for NPSE

- sbi/neural_nets/net_builders/flow.py
- sbi/utils/nn_utils.py
- tests/density_estimator_test.py
- tests/linearGaussian_snpe_test.py
Fixes #1394. 
The fix here is to add a wrapper around `MADE` and `MADEMoG` which just initializes the networks with an additional dummy feature, and replaces the `forward` call of these methods by first adding a dummy input variable which gets thrown out of the output.
> Temporary Wrappers to fix MADE

- .github/workflows/build_docs.yml
- .github/workflows/cd.yml
- .github/workflows/lint.yml
- .github/workflows/manual_test.yml
- README.md
- fixes the `uv` syntax for installing optional dependencies (was causing docs workflow to break). 
- updates manuel_test workflow to be using `uv`
> fix docs workflow

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- docs/docs/contribute.md
- docs/docs/credits.md
- docs/docs/faq/question_01_leakage.md
- docs/docs/index.md
- docs/docs/install.md
- docs/docs/reference/index.md
Resolves https://github.com/sbi-dev/sbi/issues/1434
I modified minor details among various codebase's markdown files to make them compliant with [Markdown linter](https://github.com/DavidAnson/markdownlint/tree/v0.37.4), changes mainly involved:
- Providing a consistent unordered list marker in the same MD file (`*` or `-`, but not both in the same file)
- Providing extra void lines around code blocks where they were missing
-  Providing `bash` as language definition for code block where it was missing
- Added surrounding angular parenthesis (`<https:\\url>` and not `https:\\url`) for bare URLs
- Providing an alternative image textual description for a couple images around the docs, this will improve accessibility for users but also improve SEO as main search engines do not appreciate …
> Docs: Markdown formatting compliant to Markdown Linter (solves #1434)

- sbi/neural_nets/estimators/categorical_net.py
- sbi/samplers/rejection/rejection.py
- sbi/utils/nn_utils.py
- tests/inference_on_device_test.py
during GPU tests a couple of bugs appeared, mostly for the new `CategoricalMADE`. 
I overloaded the `to` methods for the mixed density networks to avoid moving the `masks` to the device explicitly in every `forward` call.
> fix: gpu-handling for made and leakage correction

- docs/conf.py
Readthedocs does not build because it attempts to run the notebooks before converting them.
> Prevent notebook execution upon doc build

- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/nre/nre_base.py
This PR adds a warning when True is passed to the exclude_invalid_x parameter on the append_simulations method of NRE and NLE classes and updates the strings SNRE to NRE and SNLE to NLE in the docstrings.
> Add warning when using append_simulations with exclude_invalid_x=True

- sbi/samplers/rejection/rejection.py
`sample_batch` of `DirectPosterior` uses `accept_reject_sample` to generate posterior samples for a batch of observations. Changed the description of the pbar in `accept_reject_sample` to clarify how many posterior samples for how many observations are generated.
> Clarify pbar annotation in sample_batched for DirectPosterior

- sbi/neural_nets/net_builders/flow.py
Bug resolved:
The order of the transformations and standardization has been changed: we first want to standardize the input and then perform a series of transformations.
> z_score correct order in Zuko

- sbi/neural_nets/net_builders/flow.py
- sbi/utils/torchutils.py
- sbi/utils/user_input_checks_utils.py
- tests/inference_on_device_test.py
- tests/prior_device_tests.py
We implemented the `.to(device)` method for all priors supported by `sbi`. 
`CustomPriorWrapper` raises a `NotImplementedError` because `scipy` does not support `to(device)`. 
This PR will add `.to(device)` to `TorchReturnTypeWrapper`, `BoxUniform`, and `MultipleIndependent`. Corresponding tests are in `prior_device_test.py`.
> Prior to(device)

- CONTRIBUTING.md
I think this was overlooked in the recent overhaul of the documentation page.
> fix path to contribute.md

- sbi/utils/simulation_utils.py
Closes #1514 by adding a `.cpu()` before `.numpy()`
> Minor fix when moving thetas from GPU to CPU

- docs/reference/sbi.utils.rst
- docs/sbi.rst
- sbi/utils/__init__.py
- sbi/utils/pyroutils.py
This PR fixes #1511 by adding a utils section to the docs, containing just for now `to_pyro_distribution`. Because the docstrings don't indicate the model in which the function being rendered lives, I also imported `to_pyro_distribution` into `sbi.utils`. A few fixes to the docstring were required.
> Add utils to docs

- tests/embedding_net_test.py
Fixes #1532 by xfail tests that require torch.compile hence python < 3.13.
> xfail scan test on python 3.13

- sbi/inference/trainers/npse/vector_field_inference.py
- tests/inference_on_device_test.py
Following PR https://github.com/sbi-dev/sbi/pull/1527 and issue https://github.com/sbi-dev/sbi/issues/1530 , improved the test for vector field methods. 
- Added testing for training and/or sampling on device. Cross test for cpu-gpu are handled by setting two devices.
- Removed testing both on `FMPE` and `NPSE` since they are redundant (both share log_prob implementation).
- Fixed minor bug on time tensor in `_loss` function not being on the same device when moving to device the training.
- Added docstrings for GPU tests.
This one is small! Let me know if anything is missing or you think that it can be improved @StarostinV @janfb
> Gpu test for VectorFieldPosterior

- .gitignore
- README.md
- mkdocs/docs/contribute.md
- mkdocs/docs/install.md
This PR updates the documentation and readme file to support working with uv.
Fixes #1401
Bullet points from the parent issue
- figuring out what options there, e.g., how we need to update out pyproject.toml
- I haven't updated the pyproject.toml file. The project works with uv with the current configuration.
- find out whether we can speed up / improve out build process via uv (https://github.com/sbi-dev/sbi/actions/runs/10702924386)
- The current build process is configured with uv.
- adapt the readme and other installation instructions on how to use sbi via uv
- I have updated the readme and installation instructions.
> Add uv support

- tests/linearGaussian_vector_field_test.py
those tests were failing on `main` during CD. I set them to `xfail` for now. 
This needs to be fixed in #1544 (previously #1501)
> set vector field iid-tests xfail

- sbi/diagnostics/misspecification.py
- sbi/neural_nets/embedding_nets/lru.py
- sbi/neural_nets/estimators/base.py
While creating unconditional density estimator, the `sample_shape` argument of method `sample` throws error. The same goes for LRU embedding while explicitly calling for aggregate function of LRU embeddings. Changed the typedefs to match the expected types.
> Minor fix while using unconditional density estimator and LRU embedding

- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/npe/npe_base.py
- sbi/inference/trainers/nre/nre_base.py
This PR adds the `importance_sampling_parameters` argument to the docstring of the build_posterior method in the `LikelihoodEstimator`, `PosteriorEstimator`, and `RatioEstimator` classes.
> docs: Add importance_sampling_parameters to build_posterior docstring.

- CODE_OF_CONDUCT.md
- README.md
As discussed in the maintainer team, we will adopt the Code of Conduct of NumFOCUS. 
This PR updates the CoC files and relevant links.
> switch to numfocus code of conduct

- sbi/diagnostics/lc2st.py
- tests/lc2st_test.py
This PR improves the equality check for the Local-C2ST coverage get score method.
Fixes: #1549
> fix: replace 'in' operator with '==' for proper classifier comparison

- sbi/inference/trainers/marginal/marginal_base.py
- sbi/neural_nets/factory.py
- tests/marginal_estimator_test.py
The new `pyright` version detected inconsistencies in our new `Literal["flow", "options"]` in `marginal_nn` (failing on `main`). 
this PR adds an `Enum` on the different flow options as a workaround. Could be a blueprint for the other build functions in the factory.
> fix: add enum for flow options to fix type hints.

- sbi/diagnostics/lc2st.py
the default `None` option was disturbing the type checks. This is fixed here by setting the default value in `__init__` with types.
> fix LC2ST kwarg typing

- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/nre/nre_base.py
This PR adds missing arguments to `LikelihoodEstimator` and `RatioEstimator` docstrings for the `append_simulation` and `train` methods.
> Add missing arguments to LikelihoodEstimator and RatioEstimator docstrings.

- sbi/utils/sbiutils.py
This may be my mistake, but it seems the original:
```
len(batch_t > 1):
```
will always evaluate to True (unless batch_t has only one data point), even if there's only one batch. To use `standardizing_net()` as intended to load a pre-trained net with a dummy single-batch data, shouldn't it be:
```
len(batch_t) > 1:
```
Thanks !
> Update sbiutils.py to use one-dimensional batch

- sbi/diagnostics/sbc.py
- tests/sbc_test.py
- Refactored the SBC module for better code organization and API clarity. 
- Moved `VIPosterior` handling to the public API with a wrapper approach. 
- Added helper functions for better maintainability.
- Enhanced tests with fixtures, dedicated test cases for parallelization and batch sampling, and improved assertions.
- All changes maintain backward compatibility.
> refactor sbc funcs and tests

- sbi/samplers/rejection/rejection.py
This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> fix: resolve logger warnings

- sbi/diagnostics/misspecification.py
- sbi/inference/trainers/nle/mnle.py
- sbi/inference/trainers/nle/nle_a.py
- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/npe/__init__.py
- sbi/inference/trainers/npe/npe_a.py
- sbi/inference/trainers/npe/npe_b.py
- sbi/inference/trainers/npe/npe_base.py
- sbi/inference/trainers/npe/npe_c.py
- sbi/inference/trainers/nre/nre_a.py
- sbi/inference/trainers/nre/nre_b.py
- sbi/inference/trainers/nre/nre_base.py
- sbi/inference/trainers/nre/nre_c.py
- tests/linearGaussian_snre_test.py
This PR updates the class names `LikelihoodEstimator` to `LikelihoodEstimatorTrainer`, `RatioEstimator` to `RatioEstimatorTrainer`, and `PosteriorEstimator` to `PosteriorEstimatorTrainer`.
Fixes: #1600
> Rename inference trainer classes

- sbi/inference/posteriors/vi_posterior.py
- sbi/samplers/vi/vi_utils.py
This PR removes the use of empty lists as default values for the `parameters` and `modules` arguments in the `VIPosterior` class function definitions, as using mutable default arguments can lead to unexpected behavior.
> fix: remove empty list default argument

- sbi/neural_nets/embedding_nets/transformer.py
This really small PR simply adds the missing `raise` to the "unsupported activation function" error. It also fixes a few typos along the way.
> fix: throw exception on unsupported activation function

- sbi/diagnostics/lc2st.py
- sbi/inference/posteriors/importance_posterior.py
- sbi/inference/posteriors/mcmc_posterior.py
- sbi/inference/posteriors/vector_field_posterior.py
- sbi/inference/posteriors/vi_posterior.py
- sbi/inference/trainers/fmpe/fmpe.py
- sbi/inference/trainers/nle/mnle.py
- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/npe/mnpe.py
- sbi/inference/trainers/npe/npe_base.py
- sbi/inference/trainers/npse/npse.py
- sbi/inference/trainers/npse/vector_field_inference.py
- sbi/inference/trainers/nre/nre_base.py
This pull request replaces `build_posterior` method string type annotations with Literals on all inference trainer classes.
The refactoring is applied to the following trainers:
In addition, this PR also updates string type annotations for `posterior` class init methods with Literals.
> Refactor build posterior method arguments to use Literals

- docs/tutorials/00_getting_started.ipynb
- sbi/inference/potentials/likelihood_based_potential.py
- sbi/inference/potentials/ratio_based_potential.py
- sbi/inference/potentials/vector_field_potential.py
- sbi/inference/trainers/base.py
- sbi/inference/trainers/fmpe/fmpe.py
- sbi/inference/trainers/marginal/marginal_base.py
- sbi/inference/trainers/nle/mnle.py
- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/npe/mnpe.py
- sbi/inference/trainers/npe/npe_base.py
- sbi/inference/trainers/npe/npe_c.py
- sbi/inference/trainers/npse/npse.py
- sbi/inference/trainers/npse/vector_field_inference.py
- sbi/inference/trainers/nre/nre_base.py
- tests/linearGaussian_vector_field_test.py
- tests/posterior_nn_test.py
With the current implementation each trainer class `build_posterior` method contains duplicated logic for creating a posterior, violating the DRY principle and making it hard for modification.  
This PR adds a `build_posterior` method in the `NeuralInference` base class for handling posterior creation. With the updated implementation trainers inheriting from the `NeuralInference` base class now call the parent method to create a posterior, thus centralizing the posterior creation logic to a single place and removing duplicated conditional posterior creation logic previously found in each sub-class. 
The `density_estimator` argument is intentionally retained in the subclasses (instead of renaming to a more general name like `estimator`) to avoid breaking changes for users relying on the …
> Refactor build_posterior to Eliminate Duplication Across Trainers

- sbi/inference/trainers/base.py
- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/npe/npe_base.py
- sbi/inference/trainers/npe/npe_c.py
- sbi/inference/trainers/npse/vector_field_inference.py
- sbi/inference/trainers/nre/nre_base.py
This PR fixes return type mismatch between `NeuralInference` base class and its subclasses( `NLE`, `NPE`, and `vector_field_inference`) by updating the return type annotation for the `append_simulations` method to [Self](https://typing-extensions.readthedocs.io/en/latest/#typing_extensions.Self).
With the current implementation, `pyright` displays an error because the type checker assumes there is a type mismatch when trainer subclasses call the `append_simulations` method from the base class. This occurs because the base class method is annotated to return the base type `NeuralInference`, while subclasses return more specific types. Using the `Self` annotation resolves this problem as it correctly infers the return types.
Fixes: https://github.com/sbi-dev/sbi/issues/1453
> Update append_simulations return type to Self

- sbi/inference/posteriors/posterior_parameters.py
- sbi/inference/potentials/vector_field_potential.py
- sbi/inference/trainers/base.py
- sbi/inference/trainers/fmpe/fmpe.py
- sbi/inference/trainers/nle/mnle.py
- sbi/inference/trainers/nle/nle_base.py
- sbi/inference/trainers/npe/mnpe.py
- sbi/inference/trainers/npe/npe_base.py
- sbi/inference/trainers/npse/npse.py
- sbi/inference/trainers/nre/nre_base.py
- sbi/utils/typechecks.py
- tests/inference_on_device_test.py
- tests/posterior_nn_test.py
- tests/posterior_parameters_test.py
Currently, sbi uses string-typed code to pass configuration to the `build_posterior` methods of trainer classes. This approach makes it difficult for users to understand which values are required.
This pull request builds upon https://github.com/sbi-dev/sbi/pull/1610 by introducing data classes for creating posterior instances. These changes bring:
Instead of going over the documentation for acceptable fields, users now get auto-completion and static checks via `dataclass` definitions:
```python
from sbi.inference.posteriors.posterior_parameters import MCMCPosteriorParameters
params = MCMCPosteriorParameters(num_chains="4", warmup_steps="100", thin=1.0)
inference.build_posterior(posterior_parameters=params)
```
The fields will be automatically cast to the correct types.
```python
from …
```
> Refactor build_posterior Posterior Configuration Using Dataclasses

- sbi/inference/trainers/nle/mnle.py
- sbi/inference/trainers/nle/nle_a.py
- sbi/inference/trainers/npe/mnpe.py
- sbi/inference/trainers/npe/npe_a.py
- sbi/inference/trainers/npe/npe_b.py
- sbi/inference/trainers/npe/npe_c.py
- sbi/inference/trainers/nre/bnre.py
- sbi/inference/trainers/nre/nre_a.py
- sbi/inference/trainers/nre/nre_b.py
- sbi/inference/trainers/nre/nre_c.py
- sbi/sbi_types.py
In PR #1633, I noticed that the typing module defines `NewType` instead of using `TypeAlias`. For our purposes, an alias is just fine and comes without consequences for documentation rendering and type checking (`NewType` does not implicitly perform type checking according to the actual underlying type). Therefore: 
- Replace NewType with TypeAlias for SummaryWriter, Distribution, Tensor, Transform.
- Rename TensorboardSummaryWriter → TensorBoardSummaryWriter.
- Remove unused TorchModule alias; use torch.nn.Module where needed (e.g., NPE_A.build_posterior).
- Update imports/annotations across trainers to new alias.
Notes: 
- Type-only refactor; no behavior changes.
- Breaking rename: external imports of TensorboardSummaryWriter/TorchModule must update.
> Use TypeAlias and consistent naming for sbi types

- docs/_templates/autosummary/class.rst
- docs/how_to_guide/19_posterior_parameters.ipynb
- docs/sbi.rst
- sbi/inference/posteriors/__init__.py
This pull request adds the `PosteriorParameters` dataclasses to the Sphinx documentation.
It also updates the class template to display shorter titles to avoid long names being cut off when displaying full paths.
> Posterior parameters doc

- sbi/inference/potentials/score_fn_iid.py
- sbi/inference/potentials/vector_field_potential.py
- sbi/neural_nets/estimators/score_estimator.py
- tests/inference_on_device_test.py
fixing #1648 #1649 
@michaeldeistler or @manuelgloeckler can you test and fix this for training? 
The relevant test is `pytest tests/inference_on_device_test.py::test_VectorFieldPosterior_device_handling      
`
> fix iid-score device handling

- sbi/inference/posteriors/vector_field_posterior.py
- sbi/inference/potentials/score_fn_iid.py
- sbi/inference/potentials/vector_field_potential.py
- sbi/samplers/rejection/rejection.py
- sbi/samplers/score/diffuser.py
- tests/linearGaussian_vector_field_test.py
The slow vf tests were running for hours and were eventually killed by GH action runners. I believe there were some nested fixture calls causing this issue. This is now fixed and the runtime is "down" to 30min for the slow vf tests. 
I also did some refactoring the the vf utils here and there to make it more transparent. IID inference for FMPE is working in parts, see #1656
> Fix slow vector field tests

- sbi/analysis/sensitivity_analysis.py
- tests/sensitivity_analysis_test.py
CodeCov showed that `sensitivity_analysis.py` had a very low test coverage (~31/162 lines). I guided GPT-5 to analyze this and add tests for the missing lines. I double checked everything and it looks good to me. 
It found a bug along the way and fixed it. 
- Add targeted tests for `sensitivity_analysis.py` in sensitivity_analysis_test.py:
- Cover `Destandardize`, `destandardizing_net` (incl. single-sample branch), and `build_input_output_layer`.
- Cover `ActiveSubspace.add_property` (mlp, resnet, callable, invalid), `train` (first build, reuse, clipping), `find_directions` (regression vs posterior-log, prior stats present/absent, normalization on/off), and `project`.
- Use small tensors, few epochs, and parametrization for speed/coverage.
- Fix bug in `destandardizing_net`: replace `if …
> Add tests for sensitivity analysis
