README.md, setup.py
Added testing dependencies to `extras['dev']` in `setup.py`; updated installation instructions in `README.md`.
=> Install deps

README.md, sbi/inference/apt.py, sbi/inference/snl.py, sbi/inference/sre.py, sbi/mcmc/slice_numpy.py, sbi/simulators/nonlinear_gaussian.py, sbi/utils/__init__.py, sbi/utils/io.py
there might be a more elegant way to get the root path. any ideas?
=> Remove env var

examples/sre_lotkavolterra.ipynb, sbi/simulators/lotka_volterra.py
=> remove _summary_observations from lv simulator. adapt example

sbi/dummytests/whateverstuff.py
=> cleanup tests

sbi/inference/snl/snl.py, sbi/inference/sre/sre.py, sbi/utils/torchutils.py, tests/test_torchutils.py
- more documentation
- updated tests
=> Test fixes for make_shapes_conform

sbi/utils/get_nn_models.py
Adds keywords arguments for constructing neural networks, docstrings, and type annotations.
=> NN model interface with additional options

.github/workflows/docs.yml, .github/workflows/testing.yml, .github/workflows/tests.yml, docs/README.md, docs/docs/index.md, docs/docs/reference.md, docs/docs/static/global.css, docs/mkdocs.yml, sbi/inference/snl/snl.py, sbi/inference/snpe/snpe_a.py, sbi/inference/snpe/snpe_b.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snpe/snpe_c.py, sbi/inference/sre/sre.py, sbi/utils/get_nn_models.py
Addresses https://github.com/mackelab/sbi/issues/109 using `mkdocstrings`.
=> API reference

examples/snpec_slcp.ipynb, sbi/inference/base.py, sbi/simulators/__init__.py, sbi/simulators/simutils.py, sbi/simulators/user-input-checks.md, tests/test_simulator_utils.py
Check user input and change to have only torch functions with batch dimension. 
WIP. More details see issues #89 and #99 
To Do:
=> [WIP] User interface

.gitignore, sbi/__init__.py, sbi/version.py, setup.py
Versioning with latest commit SHA inspired by `pyro-ppl` for development
=> Version with SHA

tests/user_input_checks_test.py
this adds the tests for the prior wrappers that were deleted in the previous PR #139 . 
Will be merged into master once PR #143 is merged and this PR is rebased onto the new master.
=> add prior wrapper tests, fix imports.

docs/docs/contribute.md, docs/mkdocs.yml
A very basic version of a Contribute page for the docs. We can collect ideas of what else should go in there here -- or merge this as a starting point and discuss elsewhere
Related issues: #118, #93, #128 
Will merge on any one review
=> Add contribute page

sbi/inference/base.py, sbi/inference/snl/snl.py, sbi/inference/snpe/snpe_base.py, sbi/inference/sre/sre.py, tests/linearGaussian_snpe_test.py
This does away with a lot of redundant code for convergence checking.
A little fix along the way: SRE and SNL no longer cat tensors just to get dimensions.
Good to go with any one approval.
=> Refactor training convergence

sbi/user_input/user_input_checks.py, tests/user_input_checks_test.py
Remove UserWarning when simulator is wrapped to handle arbitrary batches
of parameters. Instead, accept simulators that can't batch, just wrap
them to return a leading batch dim to be used in sbi. Don't warn, but
inside of the simulator `assert` that batch size is equal to one.
Adapt tests.
closes #159 .
=> remove warning for no batch simulator, wrap to return leading batch dim.

sbi/inference/base.py, sbi/inference/posteriors/sbi_posterior.py, sbi/inference/snl/snl.py, sbi/inference/snpe/snpe_a.py, sbi/inference/snpe/snpe_b.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snpe/snpe_c.py, sbi/inference/sre/sre.py
This just adds a `clip_max_norm` optional argument (default 5.0) in all training loops.
Other than that, fixed types, docstrings, whitespace.
Good to go with one quick look from any of you.
=> Clip grad norm

sbi/utils/plot/plot.py
=> Addresses #179

sbi/utils/get_nn_models.py
Concerns #168 
When the output space of the density estimator is 1D, we warn for MAFs and raise an error for NSFs.
Will merge upon any review.
=> Warning or error for 1D limitations of flows

sbi/inference/base.py, sbi/inference/snle/snle_base.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snpe/snpe_c.py, sbi/inference/snre/snre_a.py, sbi/inference/snre/snre_b.py, sbi/inference/snre/snre_base.py, sbi/simulators/simutils.py, sbi/utils/__init__.py, sbi/utils/sbiutils.py, tests/inference_with_NaN_simulator_test.py, tests/linearGaussian_snpe_test.py, tests/simulator_utils_test.py
re-applies PR #178 because the merge went wrong. See that PR for history. 
closes #210 
closes #184
=> Rerevert allow nan data

sbi/utils/sbiutils.py
to remove dependency on torch 1.5.
relates to #232
=> replace torch logical functions by built-in operators.

sbi/inference/base.py, sbi/inference/posterior.py
warn for
- `default_x.setter`
- `set_default_x`
- `log_prob`
- `sample`
if a provided x does not match `self._x_o_training_focused_on`
=> warn if x!=x_o

sbi/inference/posterior.py, tests/inference_with_NaN_simulator_test.py, tests/linearGaussian_snle_test.py, tests/linearGaussian_snpe_test.py, tests/linearGaussian_snre_test.py, tests/posterior_nn_test.py
sample now takes a shape (i.e. torch.Size or tuple)  instead of an integer
=> Sample shape

sbi/inference/base.py
Changes tensorboard path for compatibility with Windows, see issue #244.
=> Tensorboard path

tests/conftest.py, tests/linearGaussian_snle_test.py, tests/linearGaussian_snpe_test.py, tests/linearGaussian_snre_test.py, tests/simulator_utils_test.py, tests/user_input_checks_test.py
=> Default tensor type through fixture

sbi/inference/posterior.py
Several updates for MCMC:
- Chains in subsequent rounds of sampling start where they previously were in accordance with the SNL paper -- rather than reinitialising
- New parameter `init_strategy` that allows initialising chains by sampling from prior or by doing Sequential Importance Resampling (finds high probability init locations)
- Slice Sampling MCMC in numpy allows for multiple chains
=> MCMC updates

sbi/inference/posterior.py
- `hmc` was not working because we had decorated the `posterior.sample()` function with `torch.no_grad()`. But `hmc` requires gradients.
- only `hmc` tracks gradients
- samples are detached after sampling (so the user does not have to care about it). For all methods but `hmc` this does not do anything.
- `posterior.sample()` now shows progressbar by default.
- when sampling with `slice_np`, I got a warning. This is fixed by casting the output samples with `.type()` instead of with `torch.tensor(..., type=)`
Will merge upon a single approval.
=> Fix HMC bug

.github/workflows/tests.yml, README.md
=> Add code coverage reporting

CHANGELOG.md, sbi/__version__.py
Planning to release 0.10.0 once https://github.com/mackelab/sbi/pull/267 is merged. Updates version and changelog
=> Prepare for v0.10.0 release

sbi/neural_nets/classifier.py
Attempt to fix https://github.com/mackelab/sbi/issues/290
=> Move StandardizeInputs outside of function for pickling

paper.bib, paper.md
I tweaked the formatting of some of the `.bib` entries, but otherwise the manuscript looks great!
=> Some formatting edits for the JOSS paper

docs/docs/faq.md, docs/docs/faq/question_03.md
See https://github.com/mackelab/sbi/pull/323 for a discussion on this.
This PR only provides the FAQ, all other code remains unchanged.
Provides a fix for #317.
=> FAQ for serializing with dill

sbi/utils/sbiutils.py
Fixing the bug described in #324
=> Fixing the bug found in sbi.utils.sbiutils.Standardize

CHANGELOG.md, sbi/inference/posteriors/direct_posterior.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snpe/snpe_c.py, sbi/utils/sbiutils.py
for the call in `leakage_correction` we use the default 10000 because the number of samples drawn is 10000 as well.
=> add sampling batch size as arg, improve docs.

sbi/inference/snle/snle_base.py
This change has no direct consequences, it is just about naming. 
Our variable names for the batches were just wrong, because in SNLE the data set is built as `(x, theta)` not as `(theta, x)`. 
Now, it is `(theta, x)` again, as one would expect, and the call to `log_prob` is changed accordingly.
=> change dataset order and log_prob call in snle.

sbi/inference/posteriors/base_posterior.py
=> move restricted prior to top level of file.

setup.py
=> depend on new nflows to fix snpe with nsf and mcmc, closes #373.

.github/workflows/tests.yml, CHANGELOG.md, sbi/__version__.py, setup.cfg, tests/conftest.py, tests/inference_on_device_test.py, tests/linearGaussian_snpe_test.py
- CI tests do not run properly.
=> Gpu support fixing CI

docs/docs/index.md
A small update with the links towards the ICML 2020 versions of the SNRE papers.
=> Small update to index.md

sbi/utils/torchutils.py
closes #414 
or not, @michaeldeistler ?
=> cast boxuniform input to float32.

CHANGELOG.md, sbi/simulators/simutils.py, setup.py
- use stackoverflow solution for updating the progress bar after joblib jobs finish: https://stackoverflow.com/a/61689175
- depend on new joblib=1.0.0
closes #418
closes #419
=> Fix multiprocessing pbar

tutorials/08_restriction_estimator.ipynb
Tutorial for the `RestrictionEstimator` introduced in #390.
=> Tutorial for restriction estimator

sbi/inference/base.py, sbi/utils/__init__.py, sbi/utils/sbiutils.py, tests/inference_with_NaN_simulator_test.py
=> add warning and test for z-scoring x with large-variance data.

CHANGELOG.md, sbi/inference/__init__.py, sbi/inference/abc/abc_base.py, sbi/inference/abc/mcabc.py, sbi/inference/abc/smcabc.py, sbi/inference/base.py, sbi/inference/posteriors/base_posterior.py, sbi/utils/__init__.py, sbi/utils/restriction_estimator.py, sbi/utils/user_input_checks.py, sbi/utils/user_input_checks_utils.py, tests/user_input_checks_test.py
=> Moving user_input_checks to utils

sbi/inference/snre/snre_a.py, tests/inference_on_device_test.py
closes #441 
thanks to @glouppe
=> fix device for gpu in snrea, add test.

sbi/inference/posteriors/base_posterior.py, sbi/inference/posteriors/direct_posterior.py, sbi/inference/posteriors/likelihood_based_posterior.py, sbi/inference/posteriors/ratio_based_posterior.py, sbi/inference/snle/snle_base.py, sbi/inference/snpe/snpe_c.py, sbi/inference/snre/snre_base.py, sbi/utils/__init__.py, sbi/utils/sbiutils.py
relates to #466 
The code is correct as it is. This PR just implements some refactoring and adds a test for non-atomic apt.
=> refactoring non-atomic apt

tests/sbiutils_test.py
The test is quite a lot of code, so I just put it in `sbiutils.py`. It's very fast though (<2 seconds)
=> Added test for non-atomic APT

sbi/inference/snle/snle_base.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snre/snre_base.py, sbi/utils/restriction_estimator.py, sbi/utils/user_input_checks.py, tests/user_input_checks_test.py
This is not the best fix on the face of this planet, but it works. Let me know what you think!
Closes #460
=> moving fresh NN to same device as base class

sbi/utils/user_input_checks.py
just a minor thing, but I get this warning often :)
=> Fix f-string in device-realated warning

CONTRIBUTING.md
=> isort>4 no longer needs -y flag

environment.yml, sbi/inference/snpe/snpe_a.py, setup.py, tests/inference_on_device_test.py, tests/user_input_checks_test.py
- add SNPE-A to device tests
- fix device handling 
- depend on new `pyknos` with bug fix
Tests will pass once `pyknos` https://github.com/mackelab/pyknos/pull/19 is merged and released.
=> Fix snpe a device handling

sbi/utils/plot.py
replacement for #472 because that fork + merge became a mess
=> added more verbose description for probs2contours

sbi/examples/minimal.py
just discovered this when looking for an example with a gaussian prior
=> fix deprecated API usage so that minimal.py does not throw anymore

.vscode/settings.json, sbi/inference/posteriors/base_posterior.py, sbi/utils/__init__.py, sbi/utils/sbiutils.py
This PR allows to load older posteriors under the latest changes relating to `iidx`
=> Add iidx attributes to __setstate__()

sbi/inference/posteriors/likelihood_based_posterior.py, sbi/inference/posteriors/ratio_based_posterior.py
This is the commit to fix SRE with gpu. It also has a tiny fix for SNL with gpu
=> bugfix for device handling in SNRE

sbi/inference/posteriors/direct_posterior.py, sbi/inference/posteriors/likelihood_based_posterior.py, sbi/inference/posteriors/ratio_based_posterior.py
Replacement for #494 (which had git problems...)
The samplers run through for all three methods.
=> track gradients only for hmc pyro methods

sbi/inference/abc/smcabc.py, sbi/simulators/linear_gaussian.py, tests/abc_test.py
=> fix within prior checks.

sbi/inference/posteriors/base_posterior.py, sbi/utils/user_input_checks.py
when dealing with iid `xo` and sampling from the posterior for a specified `x`, `posterior.sample((10,), x=xo)` and no `default_x` was set before, we do not check whether the passed `x` matches the internal `x_shape`. This PR fixes this.
=> add check for x shape when there is no default x.

sbi/inference/posteriors/base_posterior.py, sbi/inference/posteriors/direct_posterior.py, sbi/inference/posteriors/likelihood_based_posterior.py, sbi/inference/posteriors/ratio_based_posterior.py, sbi/inference/snle/snle_a.py, sbi/inference/snpe/snpe_a.py, sbi/inference/snpe/snpe_c.py, sbi/inference/snre/snre_a.py, sbi/inference/snre/snre_b.py, sbi/utils/torchutils.py, tests/inference_on_device_test.py, tests/user_input_checks_test.py
=> add process device for to box uniform.

sbi/analysis/plot.py, sbi/utils/plot.py
=> adapt plotting to take ax and fig.

sbi/inference/snpe/snpe_base.py
Clean-up after the sampler PR.
=> Bugfix: remove warning when snpe-c with mdn is used

sbi/inference/posteriors/mcmc_posterior.py
Question @jan-matthis @janfb: Should we even set `slice_np_vectorized` as the default?
=> Advertise slice_np_vectorized

sbi/inference/base.py, sbi/inference/snle/snle_a.py, sbi/inference/snle/snle_base.py, sbi/inference/snpe/snpe_a.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snpe/snpe_c.py, sbi/inference/snre/snre_a.py, sbi/inference/snre/snre_b.py, sbi/inference/snre/snre_base.py, tutorials/11_sampler_interface.ipynb
will close the other pull request #596 , because of branching it of the wrong branch.
Adressed black formatting issues.
=> Retrain_from_scratch renaming

sbi/inference/snle/snle_base.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snre/snre_base.py
this renames variables that had confused `log_prob` and `loss`.
Also, it adds logging of `train_log_probs` to SNLE and SNRE.
=> Renaming variables in the .train() method

sbi/analysis/plot.py, sbi/analysis/sensitivity_analysis.py, sbi/utils/conditional_density_utils.py, tests/analysis_test.py, tests/inference_on_device_test.py
Fixes #538 
In a separate, independent, commit, it also adds tests for `DirectPosterior` on GPU.
=> GPU fixes for analysis modules

sbi/inference/posteriors/mcmc_posterior.py, sbi/samplers/mcmc/__init__.py, sbi/samplers/mcmc/init_strategy.py, tests/linearGaussian_snle_test.py
=> MCMC: rename `prior` init to `proposal`

sbi/inference/posteriors/base_posterior.py, sbi/utils/__init__.py, sbi/utils/posterior_ensemble.py, tests/ensemble_test.py
First draft for a posterior ensemble wrapper based on @jan-matthis conceptual code in #106.
=> first draft of NeuralPosteriorEnsemble Wrapper (addressing #106).

sbi/inference/snle/snle_base.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snre/snre_base.py
=> Bugfix for build_posterior()

sbi/inference/snpe/snpe_a.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snpe/snpe_c.py, tests/linearGaussian_snpe_test.py
closes #652 
It also solves a bug in SNPE_A
=> Snpe first round loss

sbi/utils/sbiutils.py
=> add atol to check transform.

sbi/analysis/plot.py
The changes from `marginal_plot` had broken the `subset` argument of `pairplot`. This fixes it.
=> Bugfix for pairplot

sbi/inference/snle/snle_base.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snre/snre_base.py
=> use only training data for neural net building.

sbi/inference/snpe/snpe_base.py, sbi/neural_nets/embedding_nets.py, tests/embedding_net_test.py
=> IID embedding net tests

sbi/utils/user_input_checks.py
see #752 
I see no need for splitting `prepare_for_sbi` because we already have separate `process_prior` and `process_simulator`. All `prepare_for_sbi` does is applying them both and then checking again. 
I improved documentation for `process_prior` and `process_simulator` to make this more obvious to users.
=> improve docstrings for prior and simulator preparation

sbi/neural_nets/embedding_nets.py
This is a PR to be merged into your CNN branch.
Not sure if I missed something in the implementation, but the tests pass.
=> cnn shapes in loop

sbi/inference/snpe/snpe_base.py
=> Fixup for excluding NaN in NPE

sbi/utils/user_input_checks.py, tests/simulator_utils_test.py, tests/user_input_checks_test.py
=> fix process simulator for multi-d x, adapt tests.

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/docs/code_of_conduct.md, docs/mkdocs.yml
=> code of conduct.

sbi/inference/abc/abc_base.py, tests/abc_test.py
=> fix abc custom distance.

sbi/utils/user_input_checks.py, tests/user_input_checks_test.py
improve typing and docs. 
process sequences of prior recursively, see #746 , #752
=> doc: custom and independent prior handling.

sbi/utils/sbiutils.py
=> doc: improve z-scoring warning.

.vscode/settings.json, sbi/inference/posteriors/direct_posterior.py, sbi/inference/snpe/snpe_a.py, sbi/inference/snpe/snpe_base.py, sbi/inference/snpe/snpe_c.py, sbi/types.py, setup.py
see #847 
I started fixing black and pyright errors. But there are hundreds of other pyright errors, so we need a more general solution. 
@michaeldeistler let's discuss.
=> Fix pyright errors

docs/mkdocs.yml, tutorials/17_vi_posteriors.ipynb
Hi, 
Here is a tutorial on using a variational inference posterior for the docs.
=> Add SNVI Tutorial in Docs

setup.py
=> pin pyro <1.8.5

tutorials/01_gaussian_amortized.ipynb
=> fixed typo in tutorial

sbi/simulators/simutils.py, sbi/utils/sbiutils.py
Casting seed to int (random seed is also casted)
Issue:
- When using Parallel this method gets a tensor, which throws an error since Pyhton 3.11
=> 873 seed error in simulator

.vscode/settings.json, sbi/inference/abc/abc_base.py, sbi/inference/abc/mcabc.py, sbi/inference/abc/smcabc.py, setup.cfg
fix for #872 and some general refactoring.
=> Refactor abc methods

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .pre-commit-config.yaml, .vscode/.ropeproject/config.py
=> add pull request template

docs/docs/faq/question_05.md
FAQ entry on moving objects pickled on GPU to a CPU.
=> FAQ: load inference pickle on CPU

CONTRIBUTING.md
=> fix #945: update guidelines, add ref to CoC.

.github/PULL_REQUEST_TEMPLATE.md
=> add license change to pr template.

.github/workflows/tests.yml
- update ref to token
- use v4 beta as in Codecov docs
- turn off CI failing
=> fix codecov token, turn off CI fail.

.pre-commit-config.yaml, pyproject.toml
Upgrade ruff from v0.2.2 to v0.3.3
No, but I obtained different results from the pre-commit ruff and the CLI with v0.2.2.
...
...
your code.
=> Upgrade ruff to 0.3.3

sbi/neural_nets/density_estimators/shape_handling.py, tests/base_test.py, tests/density_estimator_test.py, tests/inference_on_device_test.py
First step towards #1041. This provides the utility that will be used by `Posterior`, `Potential`, and `Inference`.
your code.
=> Add utility to shape inputs to (batch,iid,event)

sbi/neural_nets/density_estimators/shape_handling.py, tests/density_estimator_test.py
Following the [conventions of `pytorch`](https://bochang.me/blog/posts/pytorch-distributions/), we are changing how shapes will be interpreted in `sbi`:
`(iid, batch, event)`
your code.
=> Change shape handling to iid,batch,event

sbi/inference/potentials/likelihood_based_potential.py, sbi/neural_nets/density_estimators/__init__.py, sbi/neural_nets/density_estimators/base.py, sbi/neural_nets/density_estimators/categorical_net.py, sbi/neural_nets/density_estimators/mixed_density_estimator.py, sbi/neural_nets/mnle.py
restructured MNLE/categorical distributions and adapted to new framework
Fixes # (issue)
...
...
your code.
=> 968 adapt mnle to new densityestimator abstraction

tests/linearGaussian_snle_test.py
=> fix snpe-a tests.

docs/mkdocs.yml, examples/00_HH_simulator.ipynb
This should fix the rendering bugs on the website i.e. MathJax does require a few more curly brackets for colorings to work.
=> Fixes rendering bug on website

tutorials/05_embedding_net.ipynb
=> bugfix for tutorial on embedding net

docs/docs/reference/models.md
=> fix: docs path

tests/linearGaussian_snpe_test.py, tests/linearGaussian_snre_test.py, tests/sbc_test.py, tests/tarp_test.py
- remove remaining `simulate_for_sbi` to make `main` pass.
=> refactor: remove simulate_for_sbi from tests/

docs/docs/reference/inference.md, docs/docs/reference/models.md, docs/docs/reference/posteriors.md, docs/docs/reference/potentials.md
- fix API references links in docs
- add flow and score matching.
=> docs: fix api refs

docs/docs/index.md, tutorials/16_implemented_methods.ipynb
=> docs: typo in implemented methods

pyproject.toml
=> Fixup for pyproject.toml

.devcontainer/Dockerfile, .github/workflows/build_codespace_image.yaml
fixes #1251 by adding a dispatch workflow to the docker GH action.
=> build: devcontainer update

.devcontainer/Dockerfile
=> fix: docker notebook python version

tests/tutorials_test.py
fixes the problem explained here: https://github.com/sbi-dev/sbi/pull/1256#issuecomment-2326739994
related to #1256
=> fix: test all tutorials

sbi/inference/trainers/nle/nle_base.py, sbi/inference/trainers/npe/npe_base.py, sbi/inference/trainers/npse/npse.py, sbi/inference/trainers/nre/bnre.py, sbi/inference/trainers/nre/nre_a.py, sbi/inference/trainers/nre/nre_b.py, sbi/inference/trainers/nre/nre_c.py
fixes #1347 
add a check to all `_loss` methods.
=> add nan check to _loss method.

sbi/diagnostics/lc2st.py, sbi/diagnostics/sbc.py, sbi/diagnostics/tarp.py, sbi/utils/diagnostics_utils.py, sbi/utils/sbiutils.py, tests/inference_with_NaN_simulator_test.py
fixes #1345 by adding nan and inf handling at the beginning of `sbc`, `tarp` and `lc2st`.
=> add nan handling in diagnostics

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE/feature_or_bugfix.md
some refactoring of our templates.
=> improve PR and issue templates

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/lint.yml
using https://docs.astral.sh/uv/guides/integration/github/
`uv` speeds up installation from 2:43min to 34sec 🚀
=> perf: speed up CI with uv

docs/docs/install.md
Updated python version to be >=3.10 everywhere on the installation guide.
Resolves #1420 
Correctly created the pull request from a feature branch.
=> Corrected python version in installation document (Revised)

tests/tutorials_test.py
Tests on `main` currently failing...
=> Fix tests for new docs

paper/paper.bib
To get consistent citations in the paper (e.g. no an extra given name).
Solution by @kyleniemeyer 🙏
=> Make sure that all names that refer to the same person are identical

tests/density_estimator_test.py, tests/mnle_test.py, tests/posterior_nn_test.py
I removed in my view unnecessary test cases here and chose better options there.
=> tests: refactor "not slow" tests to be not so slow

tests/transforms_test.py
"Solves" https://github.com/sbi-dev/sbi/issues/738 in the sense that we provide a test case for this part. Once this issues (which is known from pytorch) is solved in pytorch, the test will fail and we will notice.
=> Test for known pytorch distribution transform issue

mkdocs/docs/contribute.md
=> fix: Update documentation folder path

sbi/inference/trainers/marginal/marginal_base.py, sbi/neural_nets/factory.py, tests/marginal_estimator_test.py
- add types as `Literal` to expose all flow options to user
- refactor tests
- add docs
=> ref: update tests, add types and docs to marginal trainer

docs/README.md, docs/applications.rst, docs/index.rst
=> integrate sbi application eplorer

docs/advanced_tutorials/18_training_interface.ipynb
=> Tutorial with a more representative training loop

docs/advanced_tutorials/13_diagnostics_lc2st.ipynb
=> fixed misrendered bullet list, tested locally

sbi/diagnostics/tarp.py, tests/tarp_test.py
=> patch for torch bug in tarp, run torch.histogram with cpu-only tensor
